export interface PageSEORecord {
  route: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  searchIntent: "commercial" | "informational" | "transactional" | "navigational";
  geographicTargets: string[];
  title: string;
  metaDescription: string;
  h1: string;
  semanticEntities: string[];
  canonicalUrl: string;
}

export const SEO_METADATA_REGISTRY: Record<string, PageSEORecord> = {
  // --- CORE HOMEPAGE ---
  "/": {
    route: "/",
    primaryKeyword: "web engineering and autonomous ai systems",
    secondaryKeywords: [
      "website development",
      "3d website development",
      "custom web engineering",
      "ai agent automation",
      "nextjs development company",
    ],
    searchIntent: "commercial",
    geographicTargets: ["Global", "India", "USA"],
    title: "Navya Tech Industry | Web Engineering & Autonomous AI Systems",
    metaDescription: "Navya Tech Industry builds high-performance web systems, interactive 3D WebGL platforms, and autonomous AI agents for modern enterprises worldwide.",
    h1: "NAVYA Tech Industry",
    semanticEntities: ["Next.js 15", "React 19", "Three.js", "WebGL", "Autonomous AI Agents", "Full-Stack Web Engineering"],
    canonicalUrl: "https://www.navyatech.co.in/",
  },

  // --- CORE COMMERCIAL SEO ---
  "/build-website": {
    route: "/build-website",
    primaryKeyword: "build website",
    secondaryKeywords: ["build a website", "website building services", "build business website", "professional website builder", "custom website engineering"],
    searchIntent: "transactional",
    geographicTargets: ["Global", "USA", "India"],
    title: "Build Website | Modern High-Performance Web Engineering | Navya",
    metaDescription: "Build a high-performance business website with Next.js, React, and custom 3D WebGL. Sub-second speed, full source code ownership, and fixed $1,000 pricing.",
    h1: "Build a Website That Converts Visitors Into Revenue",
    semanticEntities: ["Full-Stack Architecture", "Core Web Vitals", "Sub-Second LCP", "TypeScript", "Next.js"],
    canonicalUrl: "https://www.navyatech.co.in/build-website",
  },
  "/create-website": {
    route: "/create-website",
    primaryKeyword: "create website",
    secondaryKeywords: ["create a website", "website creation services", "create business website", "custom web creation", "brand web development"],
    searchIntent: "transactional",
    geographicTargets: ["Global", "USA", "India"],
    title: "Create Website | Bespoke Digital Platforms & Brand Engineering | Navya",
    metaDescription: "Create a modern, high-converting digital platform tailored to your brand. Full-stack engineering, tactile claymorphic aesthetics, and lifetime code ownership.",
    h1: "Create a Website Engineered for Market Authority",
    semanticEntities: ["Brand Architecture", "UI/UX Design Systems", "High-Converting Funnels", "Web Standards"],
    canonicalUrl: "https://www.navyatech.co.in/create-website",
  },
  "/website-building": {
    route: "/website-building",
    primaryKeyword: "website building",
    secondaryKeywords: ["website building process", "how websites are built", "web development methodology", "enterprise website building", "web architecture lifecycle"],
    searchIntent: "informational",
    geographicTargets: ["Global"],
    title: "Website Building Process & Architecture Guide | Navya Tech",
    metaDescription: "Explore our disciplined 5-phase website building methodology: discovery, wireframing, Next.js engineering, lead automation, and global CDN launch.",
    h1: "The Architecture Behind High-Performance Website Building",
    semanticEntities: ["5-Phase Lifecycle", "Component Wireframing", "Technical Scoping", "Lighthouse Verification"],
    canonicalUrl: "https://www.navyatech.co.in/website-building",
  },
  "/buy-website": {
    route: "/buy-website",
    primaryKeyword: "buy website",
    secondaryKeywords: ["buy a website", "turnkey website package", "buy business website", "ready website development", "website with source code"],
    searchIntent: "transactional",
    geographicTargets: ["Global", "USA", "India"],
    title: "Buy Turnkey Website | Fixed $1,000 Package with 100% Ownership | Navya",
    metaDescription: "Buy a complete, high-performance website package for a fixed $1,000 (₹10k INR). Lifetime commercial access, complete source code, and zero platform subscriptions.",
    h1: "Buy a Turnkey Website With Zero Vendor Lock-In",
    semanticEntities: ["Fixed Pricing", "Complete Git Repository", "Lifetime Rights", "No Monthly Tax"],
    canonicalUrl: "https://www.navyatech.co.in/buy-website",
  },
  "/3d-website": {
    route: "/3d-website",
    primaryKeyword: "3d website",
    secondaryKeywords: ["3d web design", "3d website development", "immersive website", "interactive 3d website", "webgl website", "threejs website"],
    searchIntent: "commercial",
    geographicTargets: ["Global", "USA", "India"],
    title: "3D Website Development | Immersive WebGL & Three.js Experiences | Navya",
    metaDescription: "Interactive 3D websites running at silky 60fps in all browsers. Custom GLSL shaders, Three.js spatial physics, and hardware-accelerated WebGL graphics.",
    h1: "3D Websites & Immersive Spatial Experiences",
    semanticEntities: ["WebGL", "Three.js", "React Three Fiber", "GLSL Shaders", "60 FPS Optimization"],
    canonicalUrl: "https://www.navyatech.co.in/3d-website",
  },
  "/website-development": {
    route: "/website-development",
    primaryKeyword: "website development",
    secondaryKeywords: ["website development services", "web development company", "hire web developers", "custom website engineering", "nextjs development"],
    searchIntent: "commercial",
    geographicTargets: ["Global", "India", "USA"],
    title: "Website Development Company | Full-Stack Web Engineering | Navya",
    metaDescription: "Full-stack website development with Next.js 15, React 19, TypeScript, and edge runtimes. High-performance codebases engineered for speed and conversion.",
    h1: "Enterprise Full-Stack Website Development",
    semanticEntities: ["Next.js 15", "React 19", "TypeScript", "Edge Runtime", "API Integration"],
    canonicalUrl: "https://www.navyatech.co.in/website-development",
  },
  "/website-design": {
    route: "/website-design",
    primaryKeyword: "website design",
    secondaryKeywords: ["web design", "ui ux design", "professional website design", "claymorphic web design", "responsive design system"],
    searchIntent: "commercial",
    geographicTargets: ["Global", "USA", "India"],
    title: "Website Design & UI/UX Systems | Claymorphic Tactile Aesthetics | Navya",
    metaDescription: "Human-centered website design with claymorphic tactile depth, fluid typography scales, responsive grids, and conversion-optimized user flows.",
    h1: "Website Design Systems That Command Market Respect",
    semanticEntities: ["Claymorphism", "Design Tokens", "WCAG 2.1 AA", "Spatial Grids", "Micro-Interactions"],
    canonicalUrl: "https://www.navyatech.co.in/website-design",
  },
  "/custom-website": {
    route: "/custom-website",
    primaryKeyword: "custom website",
    secondaryKeywords: ["custom website development", "custom web engineering", "website from scratch", "bespoke website development", "no template web development"],
    searchIntent: "commercial",
    geographicTargets: ["Global", "USA", "India"],
    title: "Custom Website Development | Handcrafted Code & Bespoke Logic | Navya",
    metaDescription: "Bespoke custom website engineering tailored to your business logic. 0% generic templates, 100% clean TypeScript code, and sub-second loading speed.",
    h1: "Custom Website Engineering Tailored to Your Workflows",
    semanticEntities: ["Bespoke Architecture", "No-Plugin Bloat", "Custom Data Schemas", "Security Hardening"],
    canonicalUrl: "https://www.navyatech.co.in/custom-website",
  },
  "/business-website": {
    route: "/business-website",
    primaryKeyword: "business website",
    secondaryKeywords: ["business website development", "company website", "corporate website design", "professional business website", "small business website"],
    searchIntent: "commercial",
    geographicTargets: ["Global", "USA", "India"],
    title: "Business Website Development | Inbound Lead Generation Platforms | Navya",
    metaDescription: "High-converting corporate business websites with automated lead qualification, instant WhatsApp channels, and Google search dominance.",
    h1: "Business Websites Built to Acquire & Convert Customers",
    semanticEntities: ["Lead Intake", "WhatsApp Gateway", "Corporate Presence", "CRM Integration"],
    canonicalUrl: "https://www.navyatech.co.in/business-website",
  },
  "/professional-website": {
    route: "/professional-website",
    primaryKeyword: "professional website",
    secondaryKeywords: ["professional website development", "professional website design", "high trust website", "executive website", "consulting website"],
    searchIntent: "commercial",
    geographicTargets: ["Global", "USA", "India"],
    title: "Professional Website Design & Development | High-Trust Platforms | Navya",
    metaDescription: "High-trust professional website architecture engineered for advisory firms, medical practices, executive consultancies, and institutions.",
    h1: "Professional Websites Engineered for High-Trust Sectors",
    semanticEntities: ["Authority Positioning", "Client Verification", "SSL Encryption", "Executive Typography"],
    canonicalUrl: "https://www.navyatech.co.in/professional-website",
  },

  // --- COMMERCIAL PRICING ---
  "/pricing": {
    route: "/pricing",
    primaryKeyword: "website development pricing",
    secondaryKeywords: ["website cost", "website development packages", "how much does website cost", "fixed price web development", "transparent website pricing"],
    searchIntent: "transactional",
    geographicTargets: ["Global"],
    title: "Website Development Pricing | Transparent Fixed Packages | Navya",
    metaDescription: "Transparent fixed pricing: Website Package ($1,000 / ₹10k), AI Agents ($1,000 / ₹10k), and Complete Ecosystem ($1,500 / ₹119k). Zero hidden fees.",
    h1: "Transparent Commercial Packages with Lifetime Ownership",
    semanticEntities: ["$1,000 Package", "$1,500 Bundle", "$50 Maintenance", "Lifetime Commercial License"],
    canonicalUrl: "https://www.navyatech.co.in/pricing",
  },
  "/pricing/india": {
    route: "/pricing/india",
    primaryKeyword: "website development cost india",
    secondaryKeywords: ["website pricing india", "website design cost inr", "web development packages india", "website price delhi mumbai bangalore", "gst invoice web development"],
    searchIntent: "transactional",
    geographicTargets: ["India", "Mumbai", "Bangalore", "Delhi NCR"],
    title: "Website Development Cost in India | Fixed INR Packages | Navya",
    metaDescription: "Fixed-price Indian Rupee packages: Website Package (₹10,000 + GST) and Complete Ecosystem (₹₹17,000 + GST). Local UPI, NEFT, and full GST billing.",
    h1: "Fixed-Price Website Engineering for Indian Businesses",
    semanticEntities: ["₹10,000 INR", "GST Invoices", "UPI Payment", "Indian Tech Hubs"],
    canonicalUrl: "https://www.navyatech.co.in/pricing/india",
  },
  "/pricing/usa": {
    route: "/pricing/usa",
    primaryKeyword: "website development cost usa",
    secondaryKeywords: ["website pricing usa", "website cost united states", "us web development packages", "web design pricing nyc sf austin", "dollar website pricing"],
    searchIntent: "transactional",
    geographicTargets: ["USA", "New York", "San Francisco", "Austin"],
    title: "Website Development Cost in USA | Fixed USD Packages | Navya",
    metaDescription: "Fixed US Dollar packages: Website Package ($1,000) and Full Ecosystem ($1,500). Enterprise Next.js architecture, Stripe credit card, and ACH wire support.",
    h1: "Fixed-Price Website Development for US Enterprises",
    semanticEntities: ["$1,000 USD", "$1,500 Bundle", "Stripe Credit Card", "ACH Wire Transfer"],
    canonicalUrl: "https://www.navyatech.co.in/pricing/usa",
  },
  "/pricing/business-website": {
    route: "/pricing/business-website",
    primaryKeyword: "business website cost",
    secondaryKeywords: ["business website pricing", "cost of company website", "corporate website package", "business website plans", "small business website price"],
    searchIntent: "transactional",
    geographicTargets: ["Global", "USA", "India"],
    title: "Business Website Pricing & Packages | Fixed $1,000 Rate | Navya",
    metaDescription: "Complete business website package for a fixed $1,000 (₹10,000 INR). Includes Next.js full-stack frontend, CRM form integration, technical SEO, and source code.",
    h1: "Business Website Package Pricing Breakdown",
    semanticEntities: ["Fixed $1,000 Rate", "CRM Integration", "SEO Audit", "Turnkey Handover"],
    canonicalUrl: "https://www.navyatech.co.in/pricing/business-website",
  },
  "/pricing/3d-website": {
    route: "/pricing/3d-website",
    primaryKeyword: "3d website cost",
    secondaryKeywords: ["3d website pricing", "webgl development cost", "threejs website price", "interactive 3d website quote", "cost to build 3d website"],
    searchIntent: "transactional",
    geographicTargets: ["Global", "USA", "India"],
    title: "3D Website Development Pricing | WebGL & Three.js Packages | Navya",
    metaDescription: "Transparent pricing breakdown for interactive 3D WebGL websites, custom GLSL shaders, Three.js scenes, and 60fps performance optimization.",
    h1: "3D Website & WebGL Development Pricing",
    semanticEntities: ["WebGL Cost", "Shader Optimization", "Three.js Pricing", "60 FPS Guarantee"],
    canonicalUrl: "https://www.navyatech.co.in/pricing/3d-website",
  },
  "/pricing/ecommerce": {
    route: "/pricing/ecommerce",
    primaryKeyword: "ecommerce website cost",
    secondaryKeywords: ["ecommerce website pricing", "cost to build online store", "d2c store development price", "shopify alternative cost", "custom ecommerce quote"],
    searchIntent: "transactional",
    geographicTargets: ["Global", "USA", "India"],
    title: "Ecommerce Website Pricing | 0% Commission Storefronts | Navya",
    metaDescription: "Turnkey D2C digital storefront package with 0% platform transaction fees, instant checkout, inventory sync, and Stripe/Razorpay integration.",
    h1: "Ecommerce Storefront Package & Pricing",
    semanticEntities: ["0% Platform Tax", "Stripe & Razorpay", "Instant Checkout", "Catalog Engine"],
    canonicalUrl: "https://www.navyatech.co.in/pricing/ecommerce",
  },

  // --- STRATEGIC GEO HUBS ---
  "/website-development/india": {
    route: "/website-development/india",
    primaryKeyword: "website development company in india",
    secondaryKeywords: ["website development india", "web design company india", "custom website development india", "3d website development india", "best web developer india"],
    searchIntent: "commercial",
    geographicTargets: ["India", "National"],
    title: "Website Development Company in India | Fixed ₹10,000 Packages | Navya",
    metaDescription: "Leading website development company in India delivering high-performance Next.js and 3D WebGL platforms. Fixed ₹10k pricing, GST billing, and local support.",
    h1: "Website Development Company in India",
    semanticEntities: ["Indian Tech Ecosystem", "GST Billing", "UPI Integration", "INR Pricing"],
    canonicalUrl: "https://www.navyatech.co.in/website-development/india",
  },
  "/website-development/mumbai": {
    route: "/website-development/mumbai",
    primaryKeyword: "website development in mumbai",
    secondaryKeywords: ["website development company mumbai", "web design mumbai", "custom web development mumbai", "business website mumbai", "corporate web developer mumbai"],
    searchIntent: "commercial",
    geographicTargets: ["Mumbai", "Maharashtra", "India"],
    title: "Website Development in Mumbai | Corporate & Financial Web Systems | Navya",
    metaDescription: "High-trust website development for Mumbai enterprises, financial institutions, media agencies, and scaleups. Sub-second speed and fixed transparent pricing.",
    h1: "Website Development Company in Mumbai",
    semanticEntities: ["Mumbai Corporate Hub", "BKC Finance", "Media & Entertainment", "Enterprise Security"],
    canonicalUrl: "https://www.navyatech.co.in/website-development/mumbai",
  },
  "/website-development/bangalore": {
    route: "/website-development/bangalore",
    primaryKeyword: "website development in bangalore",
    secondaryKeywords: ["website development company bangalore", "web design bangalore", "startup website bangalore", "saas web development bangalore", "bengaluru web engineering"],
    searchIntent: "commercial",
    geographicTargets: ["Bangalore", "Bengaluru", "Karnataka", "India"],
    title: "Website Development in Bangalore | High-Growth Tech & Startup Web | Navya",
    metaDescription: "Engineering-grade website development in Bangalore (Bengaluru) for SaaS scaleups, AI startups, and tech companies. Fast 7-day launches and 3D WebGL.",
    h1: "Website Development in Bangalore (Bengaluru)",
    semanticEntities: ["Silicon Valley of India", "Indiranagar & Koramangala", "SaaS Scaleups", "Deep Tech"],
    canonicalUrl: "https://www.navyatech.co.in/website-development/bangalore",
  },
  "/website-development/delhi-ncr": {
    route: "/website-development/delhi-ncr",
    primaryKeyword: "website development in delhi ncr",
    secondaryKeywords: ["website development company delhi", "web design noida", "web development gurgaon gurugram", "business website delhi", "corporate web developer ncr"],
    searchIntent: "commercial",
    geographicTargets: ["Delhi NCR", "Noida", "Gurgaon", "Gurugram", "India"],
    title: "Website Development in Delhi NCR | Corporate & Startup Platforms | Navya",
    metaDescription: "Modern website development across Delhi, Noida, and Gurugram (Gurgaon). High-converting business platforms, CRM integrations, and fixed pricing.",
    h1: "Website Development in Delhi NCR (Noida & Gurgaon)",
    semanticEntities: ["Delhi Corporate Hub", "Cyber City Gurugram", "Noida Tech Sector", "Lead Generation"],
    canonicalUrl: "https://www.navyatech.co.in/website-development/delhi-ncr",
  },
  "/website-development/usa": {
    route: "/website-development/usa",
    primaryKeyword: "website development company in usa",
    secondaryKeywords: ["website development usa", "web design company usa", "custom website development usa", "3d website development usa", "american web developer"],
    searchIntent: "commercial",
    geographicTargets: ["USA", "National"],
    title: "Website Development Company in the USA | Fixed $1,000 Packages | Navya",
    metaDescription: "High-performance website development for US businesses and tech startups. Enterprise Next.js architecture, 3D WebGL, and transparent $1,000 fixed pricing.",
    h1: "Website Development Company in the USA",
    semanticEntities: ["US Business Standards", "Stripe & ACH", "USD Pricing", "Sub-Second LCP"],
    canonicalUrl: "https://www.navyatech.co.in/website-development/usa",
  },
  "/website-development/new-york": {
    route: "/website-development/new-york",
    primaryKeyword: "website development in new york",
    secondaryKeywords: ["website development company nyc", "web design new york", "manhattan web developer", "corporate website new york", "high trust web design nyc"],
    searchIntent: "commercial",
    geographicTargets: ["New York", "NYC", "Manhattan", "USA"],
    title: "Website Development in New York City | High-Trust Platforms | Navya",
    metaDescription: "Enterprise website development for New York City financial practices, advisory firms, media companies, and startups. Ultra-fast Next.js architecture.",
    h1: "Website Development in New York City",
    semanticEntities: ["Manhattan Finance", "Madison Avenue Media", "High-Trust Corporate", "Executive UI/UX"],
    canonicalUrl: "https://www.navyatech.co.in/website-development/new-york",
  },
  "/website-development/san-francisco": {
    route: "/website-development/san-francisco",
    primaryKeyword: "website development in san francisco",
    secondaryKeywords: ["website development company san francisco", "web design bay area", "ai startup website sf", "silicon valley web developer", "3d web design san francisco"],
    searchIntent: "commercial",
    geographicTargets: ["San Francisco", "Bay Area", "Silicon Valley", "California", "USA"],
    title: "Website Development in San Francisco | AI & 3D Web Systems | Navya",
    metaDescription: "Cutting-edge website development in San Francisco and the Bay Area. Specializing in AI startup platforms, interactive 3D WebGL, and high-velocity launches.",
    h1: "Website Development in San Francisco & Silicon Valley",
    semanticEntities: ["Silicon Valley", "Bay Area AI", "WebGL Shaders", "Venture Scaleups"],
    canonicalUrl: "https://www.navyatech.co.in/website-development/san-francisco",
  },
  "/website-development/austin": {
    route: "/website-development/austin",
    primaryKeyword: "website development in austin",
    secondaryKeywords: ["website development company austin", "web design austin texas", "startup website austin", "silicon hills web developer", "business website austin tx"],
    searchIntent: "commercial",
    geographicTargets: ["Austin", "Texas", "Silicon Hills", "USA"],
    title: "Website Development in Austin, TX | Silicon Hills Tech Platforms | Navya",
    metaDescription: "High-performance website development for Austin, Texas startups, technology scaleups, and local enterprises. Sub-second speed and fixed $1,000 pricing.",
    h1: "Website Development in Austin, Texas",
    semanticEntities: ["Silicon Hills", "Austin Tech Boom", "Growth Scaleups", "Next.js Performance"],
    canonicalUrl: "https://www.navyatech.co.in/website-development/austin",
  },
};

export function getSEORecord(route: string): PageSEORecord | undefined {
  const clean = route.split("?")[0].replace(/\/$/, "") || "/";
  return SEO_METADATA_REGISTRY[clean];
}

export function getAllSEORecords(): PageSEORecord[] {
  return Object.values(SEO_METADATA_REGISTRY);
}
