import { SubpageConfig } from "@/components/templates/GenericSubpage";

export const commercialPages: Record<string, SubpageConfig> = {
  "/build-website": {
    slug: "/build-website",
    category: "Commercial Web Engineering",
    title: "Build Website | Modern Web Architecture by Navya Tech Industry",
    h1: "Build Website",
    primaryKeyword: "build website",
    metaDescription: "Build a high-performance, conversion-engineered website with Navya Tech Industry. Built on Next.js with sub-second speeds and full lifetime source code ownership.",
    breadcrumbs: [{ label: "Build Website" }],
    heroDescription: "Eliminate generic templates. We build custom, high-speed digital web platforms powered by Next.js, WebGL 3D interactions, and enterprise-grade SEO architecture.",
    heroImageAlt: "Build Website",
    heroImageSrc: "/ai1.png",
    heroStats: [
      { label: "Delivery Timeline", value: "7-14 Days" },
      { label: "Core Web Vitals", value: "Sub-Second" },
      { label: "Source Code Rights", value: "100% Owned" },
    ],
    overviewTitle: "Why Building with Navya Outperforms Out-of-the-Box Site Builders",
    overviewDescription: "Most modern businesses suffer from bloated WordPress plugins or slow template builders that cripple conversion rates. Navya engineers bespoke web architectures using modern TypeScript, Tailwind CSS, and edge caching to deliver maximum conversion and top-tier SEO rankings.",
    overviewCards: [
      {
        title: "Sub-Second Latency",
        description: "Zero bloat. Built with Next.js static and server rendering to ensure instant page transitions and maximum user retention.",
        badge: "Performance",
        points: ["Lighthouse score 95+", "Edge CDN delivery", "Optimized asset pipeline"],
      },
      {
        title: "Conversion-Focused UX",
        description: "Every layout, button, and typography hierarchy is designed with behavioral psychology to guide visitors toward action.",
        badge: "Conversion",
        points: ["High-intent CTAs", "Zero-friction intake forms", "Mobile-first responsive"],
      },
      {
        title: "Lifetime Ownership",
        description: "You receive clean, documented source code repository with zero proprietary vendor lock-in or recurring builder fees.",
        badge: "Asset Control",
        points: ["Full GitHub transfer", "Deploy anywhere", "No monthly builder tax"],
      },
    ],
    capabilitiesTitle: "What You Receive When We Build Your Website",
    capabilitiesSubtitle: "Full-Stack Deliverables",
    capabilities: [
      {
        title: "Bespoke Visual Design",
        description: "Tailored UI design systems matching your exact brand identity with claymorphic surfaces, sleek contrast, and custom typography.",
        badge: "Design",
        points: ["Interactive Figma blueprints", "Dark & light themes", "Micro-animations"],
      },
      {
        title: "Full-Stack Web Engineering",
        description: "Engineered with React 18, Next.js, and TypeScript for impenetrable reliability, security, and effortless scalability.",
        badge: "Engineering",
        points: ["Type-safe codebase", "REST/GraphQL API support", "Modular components"],
      },
      {
        title: "Technical SEO & Schema",
        description: "Structured JSON-LD schema, dynamic metadata, XML sitemaps, and robots configuration for guaranteed search crawler indexation.",
        badge: "Growth",
        points: ["Automated OpenGraph tags", "Canonical hierarchy", "Semantic HTML5"],
      },
    ],
    processTitle: "How We Build Your Website",
    processSubtitle: "A battle-tested 5-phase delivery process built for speed and precision.",
    processSteps: [
      {
        number: "01",
        title: "Discovery & Blueprint",
        description: "We analyze your business model, target audience, conversion paths, and compile a comprehensive architectural roadmap.",
        deliverables: ["Product specification", "Sitemap hierarchy", "Wireframe concepts"],
      },
      {
        number: "02",
        title: "Tactile UI/UX Design",
        description: "We design custom claymorphic interface components with typography hierarchies and interactive states.",
        deliverables: ["High-fidelity UI mockups", "Design token definitions", "Mobile interaction models"],
      },
      {
        number: "03",
        title: "Next.js & WebGL Engineering",
        description: "Translating mockups into clean, lightning-fast code with zero dependencies and GPU-accelerated motion.",
        deliverables: ["React component codebase", "Dynamic routing", "Interactive 3D shaders"],
      },
      {
        number: "04",
        title: "Automated QA & Performance Audit",
        description: "Testing across browsers, viewports, mobile devices, and running Core Web Vitals optimizations.",
        deliverables: ["Lighthouse audit verification", "Cross-browser test pass", "Accessibility compliance"],
      },
      {
        number: "05",
        title: "Launch & Source Code Handover",
        description: "Zero-downtime deployment to Vercel/AWS Edge CDN and complete repository transfer with full administrator rights.",
        deliverables: ["Production live deployment", "GitHub repository transfer", "Support documentation"],
      },
    ],
    differentiators: [
      {
        title: "Zero Builder Bloat",
        description: "No slow plugins or security vulnerabilities. Clean code built strictly for your operational needs.",
        badge: "Speed",
      },
      {
        title: "Transparent Fixed Pricing",
        description: "Complete website packages starting at $1,000 / ₹79,000 with clear milestones and no hidden fees.",
        badge: "Pricing",
      },
      {
        title: "Integrated AI Ready",
        description: "Pre-wired for autonomous lead qualification and chatbot automation assistants.",
        badge: "AI-Ready",
      },
      {
        title: "Direct Engineer Access",
        description: "Direct line of communication with our senior development and design team.",
        badge: "Support",
      },
    ],
    faqs: [
      {
        question: "How long does it take to build a website with Navya?",
        answer: "Our standard commercial website builds are typically delivered in 7 to 14 business days, depending on scope and custom feature requirements.",
      },
      {
        question: "Do I own the source code after launch?",
        answer: "Yes, 100%. You receive complete ownership of all repository code, assets, and deployment configurations with zero recurring software lock-ins.",
      },
      {
        question: "What technology stack do you use to build websites?",
        answer: "We use Next.js, React, TypeScript, Tailwind CSS, WebGL/Three.js shaders, and deploy on globally distributed Edge CDNs such as Vercel or AWS.",
      },
    ],
    relatedLinks: [
      {
        title: "Website Development",
        description: "Discover our full-stack engineering and development capabilities.",
        href: "/website-development",
        category: "Services",
      },
      {
        title: "Website Design",
        description: "Explore our UI/UX design systems and visual philosophy.",
        href: "/website-design",
        category: "Services",
      },
      {
        title: "Commercial Packages",
        description: "View our transparent $1,000 website packages.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Submit your project requirements and start today.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/create-website": {
    slug: "/create-website",
    category: "Commercial Web Engineering",
    title: "Create Website | Professional Brand Web Creation by Navya",
    h1: "Create Website",
    primaryKeyword: "create website",
    metaDescription: "Create a standout website for your business, brand, or enterprise. Modern Next.js engineering, bespoke UX, and maximum performance by Navya Tech Industry.",
    breadcrumbs: [{ label: "Create Website" }],
    heroDescription: "Transform your vision into an authoritative, conversion-driven digital presence. We create websites built for credibility, speed, and enduring brand equity.",
    heroImageAlt: "Create Website",
    heroImageSrc: "/ai2.png",
    heroStats: [
      { label: "Design Fidelity", value: "Bespoke" },
      { label: "SEO Indexing", value: "100% Ready" },
      { label: "Pricing Starting", value: "$1,000" },
    ],
    overviewTitle: "Website Creation Built for Long-Term Market Leadership",
    overviewDescription: "Creating a website is not just about placing elements on a page—it is about designing a persuasive digital asset that articulates your company's unique value, outperforms competitors on Google, and converts casual traffic into high-value opportunities.",
    overviewCards: [
      {
        title: "Brand Authority",
        description: "Distinct visual styling with custom typography, claymorphic lighting, and refined spacing that commands instant respect.",
        badge: "Identity",
        points: ["Custom design tokens", "Polished dark aesthetics", "Cohesive brand narrative"],
      },
      {
        title: "Flawless Multi-Device UX",
        description: "Engineered specifically for fluid responsiveness across phones, tablets, laptops, and ultra-wide displays.",
        badge: "Responsive",
        points: ["Touch-optimized interfaces", "Dynamic layout scaling", "Zero visual layout shifts"],
      },
      {
        title: "High-Speed Infrastructure",
        description: "Static generation and edge routing ensure every visitor experiences instantaneous sub-second load speeds.",
        badge: "Speed",
        points: ["Edge CDN caching", "Optimized WebP assets", "Minimal JS bundles"],
      },
    ],
    capabilitiesTitle: "What is Included in Our Website Creation Service",
    capabilitiesSubtitle: "Comprehensive Deliverables",
    capabilities: [
      {
        title: "Custom Interactive Interfaces",
        description: "Tactile micro-animations, glassmorphic accents, and smooth scrolling that engage visitors effortlessly.",
        badge: "UI/UX",
        points: ["Framer Motion animations", "Interactive state feedback", "Zero layout clutter"],
      },
      {
        title: "Lead Generation Engines",
        description: "Integrated inquiry forms, quick consultation booking, and seamless phone/WhatsApp triggers.",
        badge: "Conversion",
        points: ["Confetti conversion feedback", "Spam-protected forms", "Automated email routing"],
      },
      {
        title: "Complete Hosting & Domain Setup",
        description: "We handle SSL certification, DNS configuration, and automated continuous deployment workflows.",
        badge: "Infrastructure",
        points: ["Free SSL certificate", "Vercel / Cloudflare edge", "Global latency < 50ms"],
      },
    ],
    faqs: [
      {
        question: "Can Navya create websites for both startups and established enterprises?",
        answer: "Yes. Our architecture scales effortlessly from high-velocity startup launch sites to enterprise-grade multi-page business platforms.",
      },
      {
        question: "What do I need to provide to create a website with Navya?",
        answer: "A brief overview of your business, logo assets (if available), and your primary goals. Our team handles copy refinement, architecture, design, and code.",
      },
    ],
    relatedLinks: [
      {
        title: "Build Website",
        description: "Explore our complete website build framework.",
        href: "/build-website",
        category: "Commercial",
      },
      {
        title: "Custom Website",
        description: "Learn about our custom-tailored web engineering approach.",
        href: "/custom-website",
        category: "Commercial",
      },
      {
        title: "Pricing Packages",
        description: "Explore our fixed commercial packages.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Start creating your website today.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/website-building": {
    slug: "/website-building",
    category: "Commercial Web Engineering",
    title: "Website Building | Complete End-to-End Process by Navya",
    h1: "Website Building",
    primaryKeyword: "website building",
    metaDescription: "Discover Navya Tech Industry's disciplined website building methodology. From technical specifications to global deployment, explore how we build modern web systems.",
    breadcrumbs: [{ label: "Website Building" }],
    heroDescription: "A structured, transparent website building methodology engineered for high velocity, flawless code quality, and measurable conversion outcomes.",
    heroImageAlt: "Website Building",
    heroImageSrc: "/ai3.png",
    heroStats: [
      { label: "Milestone Transparency", value: "100%" },
      { label: "Code Coverage", value: "Type-Safe" },
      { label: "Launch Window", value: "7-14 Days" },
    ],
    overviewTitle: "A Disciplined Engineering Approach to Building Websites",
    overviewDescription: "We treat website building as a critical piece of mission-critical business infrastructure. Every route, API endpoint, component tree, and style token is designed with intentionality, avoiding technical debt and ensuring your site remains fast and maintainable for years to come.",
    overviewCards: [
      {
        title: "Architectural Planning",
        description: "We map information architecture, conversion funnels, and data structures before writing a single line of production code.",
        badge: "Architecture",
        points: ["Sitemap blueprints", "User journey mapping", "Conversion checkpoints"],
      },
      {
        title: "Modular Component Systems",
        description: "Built with reusable React components and Tailwind CSS tokens that make future additions seamless and consistent.",
        badge: "Modularity",
        points: ["Design token synchronization", "Atomic components", "Zero style collisions"],
      },
      {
        title: "Security by Design",
        description: "Impenetrable client-side architectures with zero-trust principles, content security policies, and sanitized inputs.",
        badge: "Security",
        points: ["Zero SQL/XSS vectors", "Sanitized form data", "HTTPS enforcement"],
      },
    ],
    capabilitiesTitle: "Website Building Standards",
    capabilitiesSubtitle: "Quality Benchmark",
    capabilities: [
      {
        title: "Automated Build Pipelines",
        description: "Continuous integration pipelines that automatically build, test, and validate every pull request.",
        badge: "CI/CD",
        points: ["TypeScript validation", "Asset compression", "Automated previews"],
      },
      {
        title: "Speed & SEO Optimization",
        description: "In-depth Core Web Vitals tuning for Largest Contentful Paint (LCP), Interaction to Next Paint (INP), and Cumulative Layout Shift (CLS).",
        badge: "CWV",
        points: ["Sub-second LCP", "Zero CLS layout shifts", "Instant INP responsiveness"],
      },
      {
        title: "Cross-Device Verification",
        description: "Exhaustive testing across desktop Chrome, Safari, Firefox, iOS Mobile Safari, and Android Chrome.",
        badge: "QA",
        points: ["Retina resolution scaling", "Dynamic touch targets", "Fluid typography"],
      },
    ],
    faqs: [
      {
        question: "How does Navya handle website revisions during the building process?",
        answer: "We share interactive staging previews at key milestones so you can test and provide feedback in real time before final production deployment.",
      },
      {
        question: "Can you migrate content from an existing website during the build?",
        answer: "Yes, we handle content extraction, structure enhancement, asset optimization, and 301 redirect mapping to preserve existing search rankings.",
      },
    ],
    relatedLinks: [
      {
        title: "Build Website",
        description: "View our core website building solution.",
        href: "/build-website",
        category: "Commercial",
      },
      {
        title: "Website Development",
        description: "Explore our full-stack website development stack.",
        href: "/services/website-development",
        category: "Services",
      },
      {
        title: "Request a Quote",
        description: "Get a detailed estimate for your website build.",
        href: "/request-a-quote",
        category: "Intake",
      },
      {
        title: "Pricing",
        description: "Transparent website packages.",
        href: "/pricing",
        category: "Pricing",
      },
    ],
  },

  "/buy-website": {
    slug: "/buy-website",
    category: "Commercial Web Packages",
    title: "Buy Website | Complete Turnkey Web Solutions by Navya Tech",
    h1: "Buy Website",
    primaryKeyword: "buy website",
    metaDescription: "Buy a professionally engineered website package with Navya Tech Industry. Complete turnkey development, $1,000 fixed price, lifetime code ownership, and launch support.",
    breadcrumbs: [{ label: "Buy Website" }],
    heroDescription: "Purchase a complete, production-ready website solution. Includes bespoke design, Next.js engineering, SEO foundations, domain setup, and 100% full source ownership.",
    heroImageAlt: "Buy Website",
    heroImageSrc: "/ai4.png",
    heroStats: [
      { label: "Fixed Investment", value: "$1,000" },
      { label: "India Rate", value: "₹79,000" },
      { label: "Monthly Fees", value: "$0 Builder Fee" },
    ],
    overviewTitle: "Everything Included When You Buy a Website from Navya",
    overviewDescription: "Buying a website shouldn't mean endless surprise invoices or renting your site from closed-ecosystem platforms. With Navya, you make a single transparent investment and receive a custom-engineered, fully owned digital asset that works for your business forever.",
    overviewCards: [
      {
        title: "Complete Turnkey Delivery",
        description: "From concept to deployment, we build and deliver everything: design, copy structure, code, SEO metadata, and edge hosting setup.",
        badge: "Turnkey",
        points: ["Custom UI/UX design", "Production Next.js build", "Domain and DNS activation"],
      },
      {
        title: "100% Source Code Ownership",
        description: "You receive full administrator rights to the GitHub repository. You can modify, host, or expand the code anytime with zero restrictions.",
        badge: "Full Control",
        points: ["Git repository handover", "No proprietary lock-in", "Free perpetual license"],
      },
      {
        title: "Post-Launch Support & Warranty",
        description: "We provide dedicated post-launch support and bug warranties to guarantee everything runs smoothly under live production traffic.",
        badge: "Assurance",
        points: ["30-day launch warranty", "Deployment guidance", "Telemetry monitoring"],
      },
    ],
    capabilitiesTitle: "Commercial Package Inclusions",
    capabilitiesSubtitle: "Transparent Value",
    capabilities: [
      {
        title: "Next.js + Tailwind + TypeScript Stack",
        description: "Modern, industry-standard stack used by the world's most successful tech companies.",
        badge: "Tech Stack",
        points: ["React 18 / Next.js", "Tailwind CSS v3", "Zero bloat runtime"],
      },
      {
        title: "3D WebGL Shader Accents",
        description: "Interactive visual accents and claymorphic lighting that set your brand apart from competitors.",
        badge: "Aesthetics",
        points: ["GPU-accelerated", "Mobile optimized", "Zero lag rendering"],
      },
      {
        title: "Direct Conversion Lead Funnels",
        description: "Interactive quote builders, contact modals, and instant phone / WhatsApp click-to-call triggers.",
        badge: "Leads",
        points: ["Confetti interaction", "Form validation", "Direct notifications"],
      },
    ],
    faqs: [
      {
        question: "How much does it cost to buy a website from Navya?",
        answer: "Our standard complete website package is a one-time fixed investment of $1,000 USD for global clients or ₹79,000 INR for India clients.",
      },
      {
        question: "Are there any hidden monthly subscription charges?",
        answer: "No. You own the website outright. Hosting on platforms like Vercel or Cloudflare has generous free tiers or low costs starting at $0-$20/month with no markup from us.",
      },
    ],
    relatedLinks: [
      {
        title: "Global Pricing Matrix",
        description: "Compare website, AI agent, and ecosystem packages.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "India Pricing (INR)",
        description: "Explore packages tailored in Indian Rupees.",
        href: "/pricing/india",
        category: "Pricing",
      },
      {
        title: "USA Pricing (USD)",
        description: "Explore packages tailored in US Dollars.",
        href: "/pricing/usa",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Begin your website purchase with our project intake.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/3d-website": {
    slug: "/3d-website",
    category: "Immersive Web Systems",
    title: "3D Website | High-Performance WebGL & Three.js by Navya",
    h1: "3D Website",
    primaryKeyword: "3D website",
    metaDescription: "Experience immersive, high-performance 3D websites by Navya Tech Industry. Powered by Three.js, WebGL, and custom GLSL shaders running at silky 60fps.",
    breadcrumbs: [{ label: "3D Website" }],
    heroDescription: "Captivate visitors with immersive 3D WebGL experiences and tactile shaders that elevate brand prestige without compromising on sub-second load speeds.",
    heroImageAlt: "3D Website",
    heroImageSrc: "/ai5.png",
    heroStats: [
      { label: "Frame Rate", value: "60 FPS" },
      { label: "GPU Optimization", value: "Dynamic LOD" },
      { label: "Mobile Fallback", value: "Seamless" },
    ],
    overviewTitle: "Immersive 3D Experiences Engineered for Real-World Conversion",
    overviewDescription: "Most 3D websites fail because they are heavy, slow to load, and drain mobile batteries. At Navya, we pioneer performance-conscious 3D web engineering using lightweight Three.js runtimes, procedural WebGL shaders, and adaptive level-of-detail (LOD) systems that load instantly on all devices.",
    overviewCards: [
      {
        title: "GPU-Accelerated Shaders",
        description: "Procedural vertex and fragment shaders written in GLSL that render rich lighting and depth with minimal CPU footprint.",
        badge: "WebGL",
        points: ["Custom shader pipelines", "Dynamic color palettes", "Real-time mouse interactivity"],
      },
      {
        title: "Adaptive Mobile Rendering",
        description: "Smart hardware detection that scales particle counts and draw calls dynamically to maintain 60fps on battery-saving devices.",
        badge: "Performance",
        points: ["Device capability detection", "Progressive enhancement", "Battery-friendly rendering"],
      },
      {
        title: "Storytelling & Product Showcases",
        description: "Interactive 3D product viewports that allow visitors to inspect dimensions, materials, and configurations in real time.",
        badge: "Engagement",
        points: ["Interactive orbit controls", "Smooth camera keyframes", "High visual retention"],
      },
    ],
    capabilitiesTitle: "Our 3D Web Engineering Capabilities",
    capabilitiesSubtitle: "Next-Gen WebGL",
    capabilities: [
      {
        title: "Three.js & Spline Integration",
        description: "Flawless integration of 3D scenes, physics simulations, and procedural particles inside React environments.",
        badge: "Three.js",
        points: ["React Three Fiber ready", "Spline runtime support", "Canvas viewport optimization"],
      },
      {
        title: "Plexus & Particle Networks",
        description: "Complex mathematical particle meshes and solar arc canvases that react smoothly to cursor movements.",
        badge: "Math & Physics",
        points: ["Vector particle engines", "Dynamic repulsion physics", "Smooth lerp damping"],
      },
      {
        title: "Performance & SEO Alignment",
        description: "Our 3D elements never block critical DOM rendering or Google search indexing. Full SEO markup remains instantly visible.",
        badge: "SEO Safe",
        points: ["Non-blocking canvas layers", "Static HTML SSR", "Instant LCP execution"],
      },
    ],
    faqs: [
      {
        question: "Will a 3D website slow down my Google search rankings or load times?",
        answer: "No. We architect 3D websites with non-blocking WebGL canvases and SSR HTML, ensuring sub-second Largest Contentful Paint (LCP) and perfect 95+ Lighthouse scores.",
      },
      {
        question: "Do 3D websites work on mobile phones and iPads?",
        answer: "Yes. Our engines automatically adapt shader resolution, particle density, and touch gestures to ensure fluid 60fps performance on iOS and Android devices.",
      },
    ],
    relatedLinks: [
      {
        title: "3D Website Services",
        description: "Deep dive into our 3D web development services.",
        href: "/services/3d-website-development",
        category: "Services",
      },
      {
        title: "3D Website Pricing",
        description: "View pricing packages for 3D web experiences.",
        href: "/pricing/3d-website",
        category: "Pricing",
      },
      {
        title: "Website Design",
        description: "Explore our visual UI/UX systems.",
        href: "/website-design",
        category: "Services",
      },
      {
        title: "Get Started",
        description: "Discuss your 3D website vision.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/website-development": {
    slug: "/website-development",
    category: "Engineering Services",
    title: "Website Development | Full-Stack Web Engineering by Navya",
    h1: "Website Development",
    primaryKeyword: "website development",
    metaDescription: "Full-stack website development built with Next.js, TypeScript, and modern APIs. Scalable, secure, and conversion-engineered by Navya Tech Industry.",
    breadcrumbs: [{ label: "Website Development" }],
    heroDescription: "Enterprise-grade full-stack web development engineered for performance, maintainability, and seamless digital scalability.",
    heroImageAlt: "Website Development",
    heroImageSrc: "/ai1.png",
    heroStats: [
      { label: "Frontend Stack", value: "React & Next.js" },
      { label: "Type Safety", value: "100% TypeScript" },
      { label: "API Integrations", value: "REST / GraphQL" },
    ],
    overviewTitle: "Modern Full-Stack Architecture Without Compromises",
    overviewDescription: "True website development goes far beyond aesthetics. Navya delivers robust backend integration, type-safe frontend components, edge-optimized routing, and strict security compliance to give your business an unfair technical advantage.",
    overviewCards: [
      {
        title: "Frontend Engineering",
        description: "Clean, component-driven React and Next.js applications styled with atomic Tailwind CSS and optimized for maximum speed.",
        badge: "Frontend",
        points: ["Zero runtime bloat", "Modular design tokens", "Semantic HTML5 structure"],
      },
      {
        title: "Backend & API Integration",
        description: "Seamless synchronization with headless CMS, CRM platforms, Stripe/Razorpay payment gateways, and custom microservices.",
        badge: "Backend",
        points: ["Secure webhooks", "Stripe / Razorpay payment", "CRM & lead sync"],
      },
      {
        title: "Cloud Edge Deployment",
        description: "Configured for instant worldwide distribution via Vercel, AWS CloudFront, or Cloudflare Edge with automated CI/CD.",
        badge: "DevOps",
        points: ["Zero-downtime releases", "Automated preview branches", "Global SSL & CDN"],
      },
    ],
    capabilitiesTitle: "Full-Stack Development Capabilities",
    capabilitiesSubtitle: "Technical Depth",
    capabilities: [
      {
        title: "TypeScript Full-Stack",
        description: "End-to-end type safety eliminating runtime bugs and speeding up feature development.",
        badge: "TypeScript",
        points: ["Strict mode enabled", "Shared interfaces", "Zero runtime exceptions"],
      },
      {
        title: "Accessibility & WCAG Compliance",
        description: "Screen reader-friendly markup, semantic hierarchy, keyboard navigation, and high-contrast styling.",
        badge: "Accessibility",
        points: ["WCAG 2.1 AA target", "Keyboard accessible", "Aria attributes"],
      },
      {
        title: "Automated Testing & Telemetry",
        description: "Unit testing, Playwright end-to-end verification, and real-time error logging.",
        badge: "QA & Logs",
        points: ["Playwright test suites", "Error monitoring", "Performance analytics"],
      },
    ],
    faqs: [
      {
        question: "Can Navya integrate custom APIs or third-party CRM systems?",
        answer: "Yes. We regularly build integrations with Salesforce, HubSpot, Supabase, Firebase, Stripe, WhatsApp Business, and custom REST/GraphQL backends.",
      },
      {
        question: "How do you ensure the website development is secure?",
        answer: "We employ zero-trust principles, strict Content Security Policies (CSP), input sanitization, CSRF protection, and secure HTTPS headers.",
      },
    ],
    relatedLinks: [
      {
        title: "Custom Web Development",
        description: "Custom solutions for complex enterprise requirements.",
        href: "/services/custom-web-development",
        category: "Services",
      },
      {
        title: "Web App Development",
        description: "Explore interactive web application engineering.",
        href: "/services/web-app-development",
        category: "Services",
      },
      {
        title: "Build Website",
        description: "Our complete turnkey website building package.",
        href: "/build-website",
        category: "Commercial",
      },
      {
        title: "Get Started",
        description: "Submit technical specifications for your project.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/website-design": {
    slug: "/website-design",
    category: "Design & UX Systems",
    title: "Website Design | Premium UI/UX & Claymorphic Systems by Navya",
    h1: "Website Design",
    primaryKeyword: "website design",
    metaDescription: "Award-winning website UI/UX design by Navya Tech Industry. Modern claymorphic surfaces, sleek contrast, typography hierarchy, and conversion-focused experiences.",
    breadcrumbs: [{ label: "Website Design" }],
    heroDescription: "Designing digital experiences that captivate attention and convert visitors through deliberate visual hierarchy, claymorphic depth, and flawless typography.",
    heroImageAlt: "Website Design",
    heroImageSrc: "/ai2.png",
    heroStats: [
      { label: "Design System", value: "Bespoke Tokens" },
      { label: "Typography", value: "Curated Google Fonts" },
      { label: "Theme Support", value: "Dark & Light" },
    ],
    overviewTitle: "The Art & Science of High-Conversion Visual Design",
    overviewDescription: "We reject generic SaaS templates and cookie-cutter designs. Our design philosophy fuses modern dark aesthetics, tactile claymorphic elevation, harmonious contrast ratios, and purposeful micro-interactions to create an unmistakable identity for your brand.",
    overviewCards: [
      {
        title: "Tactile Claymorphic Elevation",
        description: "Multi-layered inset and drop shadows that give buttons, cards, and navigation bars a physical, touchable quality.",
        badge: "Claymorphism",
        points: ["Multi-layer shadow tokens", "Subtle bevel lighting", "Hover scale micro-motion"],
      },
      {
        title: "Intentional Typography Hierarchy",
        description: "Carefully proportioned heading and body scales that guide visitor eye tracking smoothly down the page.",
        badge: "Typography",
        points: ["Custom font pairings", "Strict line-height ratios", "High legibility contrast"],
      },
      {
        title: "Emotional Resonance & Trust",
        description: "Clean badges, transparent proof sections, and high-contrast callouts that establish instant commercial authority.",
        badge: "Trust",
        points: ["Proof point integration", "Clean trust badges", "Zero visual noise"],
      },
    ],
    capabilitiesTitle: "Design Capabilities & Systems",
    capabilitiesSubtitle: "Craftsmanship",
    capabilities: [
      {
        title: "Complete Design Systems",
        description: "Full design token libraries covering colors, spacing, shadows, radius, and interactive component states.",
        badge: "Design Tokens",
        points: ["Tailwind configuration", "Reusable components", "Figma deliverables"],
      },
      {
        title: "Responsive Layout Geometry",
        description: "Bespoke viewport adaptations ensuring layouts look breathtaking on mobile, tablet, laptop, and 4K displays.",
        badge: "Responsive",
        points: ["Container queries", "Fluid grids", "Adaptive touch targets"],
      },
      {
        title: "Micro-Interactions & Motion",
        description: "Purposeful hover effects, scroll progress bars, and modal transitions that make browsing feel alive.",
        badge: "Motion",
        points: ["Framer Motion orchestration", "Lenis smooth scroll", "Subtle radar wave pulses"],
      },
    ],
    faqs: [
      {
        question: "Do you design websites in Figma before coding?",
        answer: "Yes. We create interactive Figma wireframes and high-fidelity prototypes for client review and feedback before proceeding to production engineering.",
      },
      {
        question: "Can Navya adapt an existing brand identity into a modern web design?",
        answer: "Absolutely. We seamlessly translate your existing logo, colors, and typography into a high-end digital design system.",
      },
    ],
    relatedLinks: [
      {
        title: "Website Development",
        description: "See how our designs come to life in code.",
        href: "/website-development",
        category: "Services",
      },
      {
        title: "Website Redesign",
        description: "Transform an outdated website into a modern showcase.",
        href: "/services/website-redesign",
        category: "Services",
      },
      {
        title: "3D Website Design",
        description: "Explore 3D and WebGL design capabilities.",
        href: "/3d-website",
        category: "Commercial",
      },
      {
        title: "Get Started",
        description: "Book your design consultation today.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/custom-website": {
    slug: "/custom-website",
    category: "Commercial Web Engineering",
    title: "Custom Website | Bespoke Web Engineering by Navya Tech Industry",
    h1: "Custom Website",
    primaryKeyword: "custom website",
    metaDescription: "Get a custom website engineered exclusively for your business goals. Zero generic templates, bespoke Next.js architecture, and 100% full source code ownership.",
    breadcrumbs: [{ label: "Custom Website" }],
    heroDescription: "Tailored specifically for unique business models that demand custom workflows, distinctive visual identity, and uncompromising performance.",
    heroImageAlt: "Custom Website",
    heroImageSrc: "/ai3.png",
    heroStats: [
      { label: "Template Dependency", value: "0% Zero" },
      { label: "Bespoke Workflows", value: "Unlimited" },
      { label: "Architecture", value: "Next.js + TypeScript" },
    ],
    overviewTitle: "Why Custom Web Engineering Wins Against Generic Templates",
    overviewDescription: "Off-the-shelf templates force your business into rigid boxes, slow down load speeds with unused scripts, and make you look identical to dozens of competitors. Navya builds custom websites from clean codebases designed around your precise conversion paths.",
    overviewCards: [
      {
        title: "Tailored User Journeys",
        description: "Every step from landing to conversion is custom-engineered to address the exact objections and expectations of your target clientele.",
        badge: "Funnels",
        points: ["Custom qualification steps", "Dynamic quote calculators", "Personalized recommendations"],
      },
      {
        title: "Unmatched Performance",
        description: "Because every line of code is written specifically for your website, there is zero dead CSS or bloated JavaScript running in the background.",
        badge: "Speed",
        points: ["Sub-second TTFB", "Clean DOM tree", "Perfect Lighthouse metrics"],
      },
      {
        title: "Infinite Extensibility",
        description: "Easily integrate AI agent networks, customer portals, internal CRM webhooks, and custom analytics without platform limits.",
        badge: "Scalability",
        points: ["Microservice ready", "Serverless API routes", "Database independent"],
      },
    ],
    capabilitiesTitle: "Bespoke Capabilities",
    capabilitiesSubtitle: "Custom Engineering",
    capabilities: [
      {
        title: "Custom Data Models & Logic",
        description: "Engineered database schemas and serverless functions tailored to your operational workflows.",
        badge: "Data Logic",
        points: ["Type-safe queries", "PostgreSQL / Firebase / MongoDB", "Fast indexing"],
      },
      {
        title: "Custom Interactive Features",
        description: "Interactive calculators, configuration tools, custom 3D model viewers, and bespoke booking flows.",
        badge: "Interactivity",
        points: ["Real-time state machines", "Confetti feedback", "Instant calculation"],
      },
      {
        title: "Zero Vendor Lock-In",
        description: "Deploy anywhere: AWS, Vercel, Netlify, or your private cloud with complete administrative sovereignty.",
        badge: "Sovereignty",
        points: ["Standard Node.js runtime", "Containerized option", "Full source transfer"],
      },
    ],
    faqs: [
      {
        question: "Is a custom website more expensive than a template site?",
        answer: "Our fixed $1,000 package makes custom web engineering accessible at prices comparable to or lower than maintaining bloated template sites over time.",
      },
      {
        question: "Can we add custom portals or member areas later?",
        answer: "Yes. Our clean component and API architecture makes adding authentication, portals, and dashboards straightforward at any time.",
      },
    ],
    relatedLinks: [
      {
        title: "Custom Web Development",
        description: "Explore our full custom development services.",
        href: "/services/custom-web-development",
        category: "Services",
      },
      {
        title: "Business Website",
        description: "See our dedicated business website solutions.",
        href: "/business-website",
        category: "Commercial",
      },
      {
        title: "Pricing Packages",
        description: "View our $1,000 custom web package.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Share your custom requirements today.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/business-website": {
    slug: "/business-website",
    category: "Commercial Solutions",
    title: "Business Website | High-Converting Corporate Web Presence by Navya",
    h1: "Business Website",
    primaryKeyword: "business website",
    metaDescription: "Professional business websites engineered to generate qualified leads and establish authority. High performance, Next.js architecture, and fixed $1,000 pricing.",
    breadcrumbs: [{ label: "Business Website" }],
    heroDescription: "Transform your company website into a 24/7 lead generation engine that commands commercial respect, ranks high on Google, and converts visitors.",
    heroImageAlt: "Business Website",
    heroImageSrc: "/ai4.png",
    heroStats: [
      { label: "Lead Conversion Focus", value: "High Intent" },
      { label: "Commercial Authority", value: "Enterprise Grade" },
      { label: "Investment", value: "$1,000 / ₹10k" },
    ],
    overviewTitle: "A Business Website Engineered to Drive Real Bottom-Line Revenue",
    overviewDescription: "Your business website is your most valuable commercial asset. We combine clear value propositions, trust-building social proof, rapid page speeds, and direct contact actions (+91 93554 12903, WhatsApp, inquiry forms) to consistently turn visitors into booked clients.",
    overviewCards: [
      {
        title: "Instant Commercial Credibility",
        description: "Structured layout with case study highlights, performance metrics, and transparent package tiers that eliminate buyer skepticism.",
        badge: "Trust",
        points: ["Proof testimonials", "Trust hero banners", "Security certifications"],
      },
      {
        title: "Multi-Channel Lead Capture",
        description: "Equipped with direct click-to-call, WhatsApp routing, email copy tools, and interactive project inquiry forms.",
        badge: "Inbound Leads",
        points: ["One-tap phone calls", "WhatsApp chat integration", "Detailed RFQ capture"],
      },
      {
        title: "Search Visibility & Local SEO",
        description: "Built-in organization schema and localized metadata to ensure your business ranks prominently for high-intent searches.",
        badge: "SEO Ranking",
        points: ["Local business schema", "Geo-targeted metadata", "Fast mobile indexation"],
      },
    ],
    capabilitiesTitle: "Business Website Inclusions",
    capabilitiesSubtitle: "Growth Features",
    capabilities: [
      {
        title: "Service Showcases & Capabilities",
        description: "Clean service grids highlighting your offerings with transparent pricing and deliverable breakdowns.",
        badge: "Services",
        points: ["Interactive cards", "Feature checklists", "Direct CTA routing"],
      },
      {
        title: "Embedded AI Assistant",
        description: "Includes the Navya Assistant chatbot to answer visitor questions 24/7 and route qualified leads directly to your inbox.",
        badge: "AI Assistant",
        points: ["Automated FAQ handling", "Instant lead alerts", "Always online"],
      },
      {
        title: "Executive Contact Architecture",
        description: "Prominently featured phone lines, email copy widgets, and calendar booking integration.",
        badge: "Contact",
        points: ["One-click copy tools", "Direct line +91 93554 12903", "Quick form intake"],
      },
    ],
    faqs: [
      {
        question: "Can we include pricing on our business website?",
        answer: "Yes! Transparent pricing builds trust and qualifies leads before they reach out. We can structure public pricing tiers or custom quote inquiry funnels.",
      },
      {
        question: "Will our team be able to update business content easily?",
        answer: "Yes. We build clean, modular components and provide clear documentation so updating text, services, and contacts is effortless.",
      },
    ],
    relatedLinks: [
      {
        title: "Business Website Services",
        description: "Deep dive into our business website engineering services.",
        href: "/services/business-website-development",
        category: "Services",
      },
      {
        title: "Business Website Pricing",
        description: "Compare packages for business websites.",
        href: "/pricing/business-website",
        category: "Pricing",
      },
      {
        title: "Professional Website",
        description: "Explore enterprise professional web standards.",
        href: "/professional-website",
        category: "Commercial",
      },
      {
        title: "Get Started",
        description: "Start building your business website.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/professional-website": {
    slug: "/professional-website",
    category: "Commercial Solutions",
    title: "Professional Website | High-Trust Enterprise Web Engineering by Navya",
    h1: "Professional Website",
    primaryKeyword: "professional website",
    metaDescription: "What makes a website truly professional? Speed, security, impeccable typography, and conversion focus. Explore Navya Tech Industry's professional web standards.",
    breadcrumbs: [{ label: "Professional Website" }],
    heroDescription: "Elevate your market perception with a professional website engineered for uncompromising speed, zero-trust security, and seamless user experience.",
    heroImageAlt: "Professional Website",
    heroImageSrc: "/ai5.png",
    heroStats: [
      { label: "Reliability Uptime", value: "99.99%" },
      { label: "Security Benchmark", value: "Zero-Trust" },
      { label: "Speed Score", value: "98/100" },
    ],
    overviewTitle: "The Anatomy of a Truly Professional Website",
    overviewDescription: "A professional website is not defined by decorative fluff or generic marketing clichés. It is defined by razor-sharp performance, accessible contrast, transparent pricing, rock-solid security, and an intuitive user experience that respects visitor time.",
    overviewCards: [
      {
        title: "Zero Layout Shifts & Instant Loading",
        description: "Sub-second response times and zero Cumulative Layout Shift (CLS) so visitors can interact with confidence immediately.",
        badge: "Speed",
        points: ["Zero jank", "Instant button feedback", "Pre-fetched routes"],
      },
      {
        title: "Impenetrable Security Standards",
        description: "Zero-trust architecture, automated CSP headers, SSL encryption, and strict protection against malicious scrapers.",
        badge: "Security",
        points: ["HTTPS strict enforcement", "Input sanitization", "OWASP top 10 compliance"],
      },
      {
        title: "Refined Design Polish",
        description: "Curated typography, claymorphic card bevels, harmonious color palettes, and accessible focus states.",
        badge: "Craft",
        points: ["Accessible focus rings", "Dark/light mode support", "Harmonious proportions"],
      },
    ],
    capabilitiesTitle: "Professional Standards We Enforce",
    capabilitiesSubtitle: "Engineering Quality",
    capabilities: [
      {
        title: "Production TypeScript Core",
        description: "Eliminating entire classes of runtime exceptions with complete type safety across all components.",
        badge: "Code Quality",
        points: ["Strict types", "Clean architecture", "Comprehensive linting"],
      },
      {
        title: "WCAG Accessibility Compliant",
        description: "Ensuring all visitors, regardless of device or ability, have a pleasant, accessible experience.",
        badge: "Accessibility",
        points: ["Screen reader support", "High contrast text", "Keyboard friendly"],
      },
      {
        title: "Global CDN Edge Delivery",
        description: "Distributed across hundreds of edge locations globally for equal speed in New York, London, and Mumbai.",
        badge: "Global Edge",
        points: ["Edge DNS", "HTTP/3 enabled", "Brotli compression"],
      },
    ],
    faqs: [
      {
        question: "Why should my company invest in a professionally engineered website?",
        answer: "A professional website establishes immediate credibility with high-value clients, improves search engine placement, and significantly increases inquiry conversion rates.",
      },
      {
        question: "How does Navya maintain consistent quality across all pages?",
        answer: "We use unified design token systems, automated Playwright test suites, and strict code review standards before any page goes live.",
      },
    ],
    relatedLinks: [
      {
        title: "Business Website",
        description: "View our business-tailored website solutions.",
        href: "/business-website",
        category: "Commercial",
      },
      {
        title: "Custom Website",
        description: "Explore custom bespoke web engineering.",
        href: "/custom-website",
        category: "Commercial",
      },
      {
        title: "Pricing Matrix",
        description: "View transparent $1,000 package tiers.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Contact Us",
        description: "Speak directly with our engineering team.",
        href: "/contact",
        category: "Contact",
      },
    ],
  },
};
