import { SubpageConfig } from "@/components/templates/GenericSubpage";

export const industryPages: Record<string, SubpageConfig> = {
  "/industries": {
    slug: "/industries",
    category: "Industry Solutions",
    title: "Industries | Tailored Digital Solutions by Navya Tech Industry",
    h1: "Industries We Power",
    primaryKeyword: "industry website development",
    metaDescription: "Explore how Navya Tech Industry engineers custom websites and automated systems tailored to the specific operational workflows of 11 distinct industries.",
    breadcrumbs: [{ label: "Industries" }],
    heroDescription: "Website engineering tailored for your exact operational reality. Explore how we build high-converting digital assets across 11 key market sectors.",
    heroImageAlt: "Industries We Power",
    heroImageSrc: "/ai4.png",
    heroStats: [
      { label: "Sectors Covered", value: "11 Industries" },
      { label: "Tailored Workflows", value: "Bespoke" },
      { label: "Lead Architecture", value: "Industry-Specific" },
    ],
    overviewTitle: "Why Industry-Specific Website Architecture Matters",
    overviewDescription: "A restaurant requires mobile menus and instant WhatsApp reservations; a SaaS company requires interactive product demos and API documentation; a healthcare clinic requires strict privacy and accessibility compliance. We build tailored architectures designed specifically for your industry's customer journey.",
    overviewCards: [
      {
        title: "Tailored Conversion Funnels",
        description: "Intake forms, scheduling tools, and call-to-actions tailored to the buying habits of your specific market.",
        badge: "Funnels",
        points: ["Custom qualification", "Industry CTA triggers", "Optimized user paths"],
      },
      {
        title: "Operational Tool Integrations",
        description: "Seamless synchronization with industry software: property MLS feeds, restaurant POS systems, and clinic calendars.",
        badge: "Integrations",
        points: ["Third-party API sync", "Custom webhooks", "Zero manual data entry"],
      },
      {
        title: "Domain Authority & SEO",
        description: "Industry-specific keyword targeting and schema markup (e.g. LocalBusiness, Restaurant, MedicalOrganization, SoftwareApplication).",
        badge: "SEO Authority",
        points: ["Industry schema", "Targeted long-tail SEO", "High local search visibility"],
      },
    ],
    capabilitiesTitle: "Explore Industry Sectors",
    capabilitiesSubtitle: "Specialized Verticals",
    capabilities: [
      {
        title: "Startups & Scaleups",
        description: "High-velocity launch websites, investor pitch decks, and waitlist engines.",
        badge: "/industries/startups",
        points: ["Rapid 7-day launch", "Waitlist conversion", "Product previews"],
      },
      {
        title: "Small Business & Local",
        description: "Cost-effective, high-impact local business websites with click-to-call and maps.",
        badge: "/industries/small-business",
        points: ["One-tap calling", "Local Google ranking", "Affordable packages"],
      },
      {
        title: "SaaS & Digital Products",
        description: "Interactive product showcases, interactive dashboards, and onboarding funnels.",
        badge: "/industries/saas",
        points: ["Feature showcases", "Pricing calculators", "Docs & onboarding"],
      },
      {
        title: "Restaurants & Hospitality",
        description: "Mobile-first digital menus, table reservations, and WhatsApp ordering.",
        badge: "/industries/restaurants",
        points: ["Fast mobile menus", "Direct WhatsApp ordering", "Table booking"],
      },
      {
        title: "Real Estate & Architecture",
        description: "High-resolution property showcases, floorplans, and inquiry capture.",
        badge: "/industries/real-estate",
        points: ["Property galleries", "Virtual tour support", "Agent inquiry forms"],
      },
      {
        title: "Healthcare & Wellness",
        description: "Accessible, patient-friendly medical practice websites with appointment requests.",
        badge: "/industries/healthcare",
        points: ["HIPAA-conscious", "Doctor profiles", "Online booking"],
      },
    ],
    faqs: [
      {
        question: "Does Navya have experience working with niche or specialized industries?",
        answer: "Yes! Our engineering team thoroughly investigates your specific customer buying behaviors, compliance requirements, and workflows before designing your site.",
      },
    ],
    relatedLinks: [
      {
        title: "Services Ecosystem",
        description: "Explore our full range of development services.",
        href: "/services",
        category: "Services",
      },
      {
        title: "Pricing Matrix",
        description: "View our fixed commercial packages.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Tell us about your industry.",
        href: "/get-started",
        category: "Intake",
      },
      {
        title: "Contact Us",
        description: "Speak with an industry specialist.",
        href: "/contact",
        category: "Contact",
      },
    ],
  },

  "/industries/startups": {
    slug: "/industries/startups",
    category: "Industries • Venture",
    title: "Startup Website Development | High-Velocity Launch Sites by Navya",
    h1: "Startup Website Development",
    primaryKeyword: "startup website development",
    metaDescription: "High-velocity website development for startups. Validate ideas, capture early waitlists, and pitch investors with modern Next.js websites by Navya.",
    breadcrumbs: [{ label: "Industries", href: "/industries" }, { label: "Startups" }],
    heroDescription: "Launch your startup fast with an authoritative, venture-grade digital presence designed to validate product-market fit, capture waitlists, and impress investors.",
    heroImageAlt: "Startup Website Development",
    heroImageSrc: "/ai1.png",
    heroStats: [
      { label: "Launch Speed", value: "7-10 Days" },
      { label: "Waitlist Capture", value: "Built-In" },
      { label: "Fixed Package", value: "$1,000" },
    ],
    overviewTitle: "Built for Velocity, Traction, and Investor Credibility",
    overviewDescription: "Startups cannot afford months of slow agency delays. We deliver production-ready, venture-caliber websites in 7 to 10 days, equipped with viral waitlist engines, confetti conversion interactions, and clean product storytelling.",
    overviewCards: [
      {
        title: "Rapid Market Validation",
        description: "Launch in days to test customer demand, collect email signups, and generate early momentum.",
        badge: "Velocity",
        points: ["Turnkey 7-day delivery", "Confetti waitlist intake", "Real-time analytics"],
      },
      {
        title: "Venture-Grade Polish",
        description: "Claymorphic visual polish, smooth Framer Motion animations, and modern dark aesthetics that elevate your pitch.",
        badge: "Credibility",
        points: ["Investor-ready design", "Product screenshot mockups", "Feature breakdowns"],
      },
      {
        title: "Developer-Friendly Code",
        description: "100% full source ownership in clean TypeScript and Next.js, allowing your in-house engineers to easily build upon it.",
        badge: "Clean Code",
        points: ["GitHub repo handover", "Type-safe components", "Zero technical debt"],
      },
    ],
    capabilitiesTitle: "Startup Inclusions",
    capabilitiesSubtitle: "Launch Stack",
    capabilities: [
      {
        title: "Waitlist & Beta Intake",
        description: "High-converting email capture with live counter and confetti celebration animations.",
        badge: "Waitlist",
        points: ["Spam-protected", "Direct email sync", "Instant notifications"],
      },
      {
        title: "Interactive Product Demos",
        description: "Shader cards and interactive previews showcasing software capabilities.",
        badge: "Demo",
        points: ["Interactive cards", "Feature tours", "Responsive preview"],
      },
      {
        title: "Full Ecosystem Bundle",
        description: "Combine your startup launch website with our autonomous AI agent pipeline.",
        badge: "Bundle",
        points: ["Website + AI Agents", "Full automation", "Starting at $1,500"],
      },
    ],
    faqs: [
      {
        question: "Can we iterate on the startup website as our product evolves?",
        answer: "Yes! You own the complete source code, and our modular component architecture makes adding new features or landing pages seamless.",
      },
    ],
    relatedLinks: [
      {
        title: "SaaS Industry Solutions",
        description: "Explore our dedicated solutions for SaaS platforms.",
        href: "/industries/saas",
        category: "Industries",
      },
      {
        title: "Landing Page Development",
        description: "High-converting campaign landing pages.",
        href: "/services/landing-page-development",
        category: "Services",
      },
      {
        title: "Pricing Matrix",
        description: "Transparent packages for startups.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Launch your startup website.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/industries/small-business": {
    slug: "/industries/small-business",
    category: "Industries • Local Business",
    title: "Small Business Website Development | High-Impact Local Sites by Navya",
    h1: "Small Business Website Development",
    primaryKeyword: "small business website development",
    metaDescription: "Affordable, high-impact website development for small businesses. Dominate local Google searches, get more phone calls, and grow with Navya Tech Industry.",
    breadcrumbs: [{ label: "Industries", href: "/industries" }, { label: "Small Business" }],
    heroDescription: "Get more phone calls and booked clients with a high-performance local business website built for trust, search dominance, and effortless mobile calling.",
    heroImageAlt: "Small Business Website Development",
    heroImageSrc: "/ai2.png",
    heroStats: [
      { label: "Fixed Package", value: "$1,000 / ₹10k" },
      { label: "Monthly Builder Tax", value: "$0 Zero" },
      { label: "Local SEO Setup", value: "Included" },
    ],
    overviewTitle: "A Commercial Website Engineered to Ring Your Phone",
    overviewDescription: "Small business owners don't need complex fluff—they need a reliable website that ranks at the top of local Google searches, displays transparent services, and makes calling (+91 93554 12903) or WhatsApp messaging completely effortless for customers.",
    overviewCards: [
      {
        title: "Direct One-Tap Calling",
        description: "Prominently featured phone triggers and WhatsApp chat buttons so mobile visitors can contact you in one tap.",
        badge: "Call Now",
        points: ["One-tap phone calls", "Instant WhatsApp chat", "Sticky mobile CTA"],
      },
      {
        title: "Local Search Dominance",
        description: "LocalBusiness structured schema, location-specific keywords, and Google Business Profile alignment.",
        badge: "Local SEO",
        points: ["LocalBusiness schema", "Google Maps integration", "Fast mobile indexation"],
      },
      {
        title: "Zero Monthly Builder Fees",
        description: "You own the website outright. Never pay expensive recurring website builder subscriptions again.",
        badge: "Ownership",
        points: ["100% full ownership", "No monthly builder fees", "Lifetime peace of mind"],
      },
    ],
    capabilitiesTitle: "Small Business Features",
    capabilitiesSubtitle: "Local Growth",
    capabilities: [
      {
        title: "Transparent Service Menus",
        description: "Clear breakdown of your services, packages, and pricing to build instant trust.",
        badge: "Pricing",
        points: ["Clear package cards", "Transparent rates", "Quick booking"],
      },
      {
        title: "Customer Testimonials",
        description: "Engaging testimonial grids showcasing reviews from satisfied local customers.",
        badge: "Social Proof",
        points: ["Verified reviews", "Customer star ratings", "Photo proof"],
      },
      {
        title: "Navya AI Assistant",
        description: "Answers customer questions 24/7 and captures appointment requests after hours.",
        badge: "AI Assistant",
        points: ["24/7 automated intake", "Lead qualification", "SMS/Email alert"],
      },
    ],
    faqs: [
      {
        question: "How easy is it for small businesses to get started with Navya?",
        answer: "Extremely easy. Fill out our simple /get-started intake form or call us at +91 93554 12903. We handle design, copywriting, coding, and launch.",
      },
    ],
    relatedLinks: [
      {
        title: "Business Website",
        description: "Explore our commercial business web package.",
        href: "/business-website",
        category: "Commercial",
      },
      {
        title: "India Pricing (INR)",
        description: "Affordable ₹79,000 packages for Indian businesses.",
        href: "/pricing/india",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Build your small business website.",
        href: "/get-started",
        category: "Intake",
      },
      {
        title: "Contact Us",
        description: "Speak with our team today.",
        href: "/contact",
        category: "Contact",
      },
    ],
  },

  "/industries/saas": {
    slug: "/industries/saas",
    category: "Industries • Software",
    title: "SaaS Website Development | High-Conversion Product Sites by Navya",
    h1: "SaaS Website Development",
    primaryKeyword: "saas website development",
    metaDescription: "High-conversion SaaS website development by Navya Tech Industry. Interactive product tours, pricing tier calculators, and developer-grade Next.js speed.",
    breadcrumbs: [{ label: "Industries", href: "/industries" }, { label: "SaaS" }],
    heroDescription: "Showcase your software with distinction. Interactive feature matrices, product walkthroughs, and conversion-optimized pricing tables built for high MRR growth.",
    heroImageAlt: "SaaS Website Development",
    heroImageSrc: "/ai3.png",
    heroStats: [
      { label: "Product Demos", value: "Interactive" },
      { label: "Pricing Model", value: "Tiered / Toggle" },
      { label: "Lighthouse Speed", value: "98/100" },
    ],
    overviewTitle: "Engineered to Lower CAC and Maximize Free-to-Paid Conversions",
    overviewDescription: "For SaaS companies, your website is the front door of your product. We build modern, highly engaging SaaS marketing websites with interactive feature demonstrations, annual/monthly pricing toggles, and seamless authentication handoffs.",
    overviewCards: [
      {
        title: "Interactive Product Walkthroughs",
        description: "Tactile shader cards and animated interface viewports showing your software's user interface in action.",
        badge: "Product Showcase",
        points: ["Live UI mockups", "Interactive feature tabs", "Micro-interaction states"],
      },
      {
        title: "Tiered Pricing Calculators",
        description: "Clear, comparison-rich pricing tables with monthly/annual discount toggles and enterprise quote triggers.",
        badge: "Pricing UX",
        points: ["Monthly/Annual toggle", "Feature comparison matrix", "Self-serve signup buttons"],
      },
      {
        title: "Developer & API Docs Ready",
        description: "Clean code snippets, REST/GraphQL endpoint highlights, and technical architecture sections.",
        badge: "Developer UX",
        points: ["Syntax-highlighted code", "SDK tabs", "API quickstart"],
      },
    ],
    capabilitiesTitle: "SaaS Engineering Features",
    capabilitiesSubtitle: "Growth Engines",
    capabilities: [
      {
        title: "Frictionless Sign-Up Flows",
        description: "Deep linking into your app's OAuth / SSO signup endpoints with zero redirect lag.",
        badge: "App Handoff",
        points: ["SSO deep links", "Pre-filled referral codes", "Instant auth"],
      },
      {
        title: "Comparison Landing Pages",
        description: "Engineered 'Vs Competitor' alternative pages that capture high-intent competitor search traffic.",
        badge: "Competitor SEO",
        points: ["Comparison tables", "Feature breakdowns", "High organic intent"],
      },
      {
        title: "Full Ecosystem AI Integration",
        description: "Deploy autonomous AI agents to qualify incoming enterprise leads and schedule product demos.",
        badge: "AI Lead Gen",
        points: ["Automated lead scoring", "Calendar sync", "Instant notifications"],
      },
    ],
    faqs: [
      {
        question: "Can you embed live interactive widgets from our SaaS product?",
        answer: "Yes! We can embed live React components, interactive sandbox calculators, or video product showreels directly into your marketing pages.",
      },
    ],
    relatedLinks: [
      {
        title: "Web App Development",
        description: "Explore custom web application services.",
        href: "/services/web-app-development",
        category: "Services",
      },
      {
        title: "Startups Solutions",
        description: "Explore startup website development.",
        href: "/industries/startups",
        category: "Industries",
      },
      {
        title: "Pricing Packages",
        description: "Transparent $1,000 / $1,500 packages.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Build your SaaS website.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/industries/restaurants": {
    slug: "/industries/restaurants",
    category: "Industries • Hospitality",
    title: "Restaurant Website Development | Menus & Direct Ordering by Navya",
    h1: "Restaurant Website Development",
    primaryKeyword: "restaurant website development",
    metaDescription: "Mobile-first restaurant website development by Navya Tech Industry. Fast digital menus, table reservation booking, and direct WhatsApp ordering with zero commissions.",
    breadcrumbs: [{ label: "Industries", href: "/industries" }, { label: "Restaurants" }],
    heroDescription: "Drive more table reservations and commission-free takeout orders with an appetizing, ultra-fast, mobile-first restaurant website.",
    heroImageAlt: "Restaurant Website Development",
    heroImageSrc: "/ai4.png",
    heroStats: [
      { label: "Commission Fee", value: "0% Zero" },
      { label: "Menu Load Speed", value: "Instant" },
      { label: "Direct Orders", value: "WhatsApp / Phone" },
    ],
    overviewTitle: "Eliminate Third-Party Commission Fees with Direct Customer Channels",
    overviewDescription: "Third-party delivery platforms take 25-30% of your restaurant's margins. We engineer beautiful, mobile-optimized restaurant websites that make browsing your food menu, reserving a table, and ordering via WhatsApp instant and enjoyable.",
    overviewCards: [
      {
        title: "Fast Mobile Food Menus",
        description: "Appetizing digital menus with dietary filters (Vegan, Gluten-Free, Halal) that load instantly without heavy PDFs.",
        badge: "Digital Menu",
        points: ["Instant category filters", "High-res food photography", "No clunky PDF downloads"],
      },
      {
        title: "Direct WhatsApp & Phone Orders",
        description: "Customers can build their order and send it directly to your restaurant's WhatsApp with one tap.",
        badge: "0% Commission",
        points: ["Pre-formatted WhatsApp cart", "One-tap phone ordering", "Zero third-party cuts"],
      },
      {
        title: "Online Table Reservations",
        description: "Frictionless table reservation forms that collect party size, date, time, and special dining requests.",
        badge: "Reservations",
        points: ["Table booking calendar", "SMS / Email confirmation", "No monthly fees"],
      },
    ],
    capabilitiesTitle: "Restaurant Capabilities",
    capabilitiesSubtitle: "Hospitality Toolkit",
    capabilities: [
      {
        title: "Location & Google Maps Routing",
        description: "Integrated maps with one-tap directions for guests driving to your venue.",
        badge: "Directions",
        points: ["Google Maps pin", "Operating hours status", "Parking details"],
      },
      {
        title: "Restaurant Structured Schema",
        description: "Restaurant JSON-LD schema showing opening hours, menu link, price range, and cuisine on Google.",
        badge: "Local SEO",
        points: ["Opening hours schema", "Menu rich snippet", "Cuisine tags"],
      },
      {
        title: "Events & Private Dining Inquiries",
        description: "Dedicated lead intake form for catering, corporate parties, and private event bookings.",
        badge: "Catering",
        points: ["Catering quote builder", "Event intake", "Instant notification"],
      },
    ],
    faqs: [
      {
        question: "Can we update our menu items and seasonal pricing easily?",
        answer: "Yes! We structure your menu in a simple, organized data file so updating items, photos, and prices takes only seconds.",
      },
    ],
    relatedLinks: [
      {
        title: "Small Business Solutions",
        description: "Explore small business website packages.",
        href: "/industries/small-business",
        category: "Industries",
      },
      {
        title: "Pricing Packages",
        description: "Transparent $1,000 / ₹79,000 packages.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Build your restaurant website.",
        href: "/get-started",
        category: "Intake",
      },
      {
        title: "Contact Us",
        description: "Speak with our team.",
        href: "/contact",
        category: "Contact",
      },
    ],
  },

  "/industries/real-estate": {
    slug: "/industries/real-estate",
    category: "Industries • Property",
    title: "Real Estate Website Development | Property Showcase by Navya",
    h1: "Real Estate Website Development",
    primaryKeyword: "real estate website development",
    metaDescription: "High-end real estate website development by Navya Tech Industry. Immersive property showcases, interactive floorplans, and high-value buyer inquiry capture.",
    breadcrumbs: [{ label: "Industries", href: "/industries" }, { label: "Real Estate" }],
    heroDescription: "Showcase luxury properties and developments with high-definition visual galleries, virtual tours, and high-intent buyer lead generation.",
    heroImageAlt: "Real Estate Website Development",
    heroImageSrc: "/ai5.png",
    heroStats: [
      { label: "Image Galleries", value: "High-Res Retina" },
      { label: "Lead Capture", value: "High Intent" },
      { label: "3D Virtual Tour", value: "Supported" },
    ],
    overviewTitle: "Elevating Property Prestige to Accelerate High-Value Transactions",
    overviewDescription: "High-net-worth buyers and investors expect an elite digital presentation. We engineer luxury real estate websites with immersive full-screen imagery, interactive floorplans, neighborhood maps, and direct VIP agent consultation forms.",
    overviewCards: [
      {
        title: "High-Resolution Property Portfolios",
        description: "Fast-loading retina image viewports, interactive video tours, and downloadable architectural brochures.",
        badge: "Showcase",
        points: ["Retina image carousels", "Matterport 3D tour embeds", "Downloadable floorplans"],
      },
      {
        title: "Filtered Property Search",
        description: "Intuitive filtering by property type, price bracket, bedrooms, square footage, and location.",
        badge: "Search UX",
        points: ["Instant client filtering", "Price range slider", "Location grid"],
      },
      {
        title: "VIP Buyer & Seller Inquiries",
        description: "Discreet, high-converting consultation forms that qualify prospective buyers and route directly to brokers.",
        badge: "Lead Funnel",
        points: ["Private viewing booking", "Broker phone direct", "WhatsApp VIP chat"],
      },
    ],
    capabilitiesTitle: "Real Estate Inclusions",
    capabilitiesSubtitle: "Property Features",
    capabilities: [
      {
        title: "Interactive Neighborhood Guides",
        description: "Showcase nearby schools, dining, transit, and lifestyle amenities with custom interactive maps.",
        badge: "Amenities",
        points: ["Custom map points", "School ratings", "Transit distance"],
      },
      {
        title: "Mortgage & ROI Calculators",
        description: "Interactive calculators allowing prospective buyers to estimate monthly payments and investment yields.",
        badge: "Calculators",
        points: ["Dynamic interest rates", "Down payment slider", "Instant calculation"],
      },
      {
        title: "Real Estate Schema Markup",
        description: "RealEstateListing structured data ensuring properties appear prominently in Google search results.",
        badge: "SEO",
        points: ["Listing price schema", "Property address metadata", "High local visibility"],
      },
    ],
    faqs: [
      {
        question: "Can you embed 3D virtual tours like Matterport or custom WebGL floorplans?",
        answer: "Yes! We specialize in embedding 3D Matterport tours, drone video showreels, and custom 3D WebGL building models.",
      },
    ],
    relatedLinks: [
      {
        title: "3D Website Development",
        description: "Explore 3D and WebGL architectural showcases.",
        href: "/services/3d-website-development",
        category: "Services",
      },
      {
        title: "Business Website",
        description: "Explore corporate web packages.",
        href: "/business-website",
        category: "Commercial",
      },
      {
        title: "Pricing",
        description: "View transparent package options.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Build your real estate website.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/industries/consulting": {
    slug: "/industries/consulting",
    category: "Industries • Professional",
    title: "Consulting Website Development | Thought Leadership Sites by Navya",
    h1: "Consulting Website Development",
    primaryKeyword: "consulting website development",
    metaDescription: "Authoritative website development for consulting firms and advisory practices by Navya Tech Industry. Thought leadership, case studies, and call booking.",
    breadcrumbs: [{ label: "Industries", href: "/industries" }, { label: "Consulting" }],
    heroDescription: "Establish undeniable advisory authority. Showcase proprietary frameworks, verified client case studies, and drive high-value strategy call bookings.",
    heroImageAlt: "Consulting Website Development",
    heroImageSrc: "/ai1.png",
    heroStats: [
      { label: "Call Booking", value: "Integrated" },
      { label: "Case Study UX", value: "Evidence-Based" },
      { label: "Authority Tier", value: "Executive" },
    ],
    overviewTitle: "Positioning Your Advisory Practice for Premium Retainers",
    overviewDescription: "High-ticket enterprise clients hire consultants based on credibility, depth of insight, and proven client outcomes. We build consulting websites that showcase your proprietary methodologies, client case studies, and streamlined strategy session booking.",
    overviewCards: [
      {
        title: "Executive Thought Leadership",
        description: "Clean publishing framework for whitepapers, executive commentary, frameworks, and podcasts.",
        badge: "Authority",
        points: ["Proprietary framework cards", "Clean article typography", "Downloadable whitepapers"],
      },
      {
        title: "Evidence-Based Case Studies",
        description: "Structured challenge-solution-result case studies highlighting measurable ROI and client testimonials.",
        badge: "Proof",
        points: ["Quantifiable ROI metrics", "Client video testimonials", "Industry breakdown"],
      },
      {
        title: "Seamless Call Scheduling",
        description: "Integrated calendar booking and qualification questions so you only spend time with serious prospects.",
        badge: "Call Booking",
        points: ["Strategy call booking", "Pre-call qualification", "Automated calendar sync"],
      },
    ],
    capabilitiesTitle: "Consulting Toolkit",
    capabilitiesSubtitle: "Advisory Features",
    capabilities: [
      {
        title: "Multi-Tier Service Architecture",
        description: "Clearly articulate advisory retainers, diagnostic audits, and executive workshops.",
        badge: "Packages",
        points: ["Advisory retainers", "Diagnostic audits", "Clear deliverable scope"],
      },
      {
        title: "Navya AI Assistant",
        description: "Qualifies inbound inquiries and routes enterprise opportunities directly to executive partners.",
        badge: "AI Qualification",
        points: ["Budget qualification", "Timeline check", "Immediate partner alert"],
      },
      {
        title: "Direct Calling Action",
        description: "Direct contact line (+91 93554 12903) and email copy utilities for immediate partner access.",
        badge: "Direct Contact",
        points: ["One-tap calling", "Quick email copy", "WhatsApp channel"],
      },
    ],
    faqs: [
      {
        question: "Can we integrate Calendly or Google Calendar directly?",
        answer: "Yes, we seamlessly integrate Calendly, Cal.com, or Google Calendar for direct strategy session booking.",
      },
    ],
    relatedLinks: [
      {
        title: "Professional Services",
        description: "Explore legal, accounting, and agency web solutions.",
        href: "/industries/professional-services",
        category: "Industries",
      },
      {
        title: "Book a Call",
        description: "Schedule a consultation with our team.",
        href: "/book-a-call",
        category: "Contact",
      },
      {
        title: "Pricing Matrix",
        description: "View our fixed commercial packages.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Build your consulting website.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/industries/healthcare": {
    slug: "/industries/healthcare",
    category: "Industries • Medical & Health",
    title: "Healthcare Website Development | Patient-Friendly Web Systems by Navya",
    h1: "Healthcare Website Development",
    primaryKeyword: "healthcare website development",
    metaDescription: "Accessible, patient-friendly healthcare website development by Navya Tech Industry. Fast appointment booking, doctor profiles, and privacy-conscious architecture.",
    breadcrumbs: [{ label: "Industries", href: "/industries" }, { label: "Healthcare" }],
    heroDescription: "Build patient trust with an accessible, high-speed healthcare website featuring doctor credentials, service breakdowns, and online appointment requests.",
    heroImageAlt: "Healthcare Website Development",
    heroImageSrc: "/ai2.png",
    heroStats: [
      { label: "Accessibility", value: "WCAG Compliant" },
      { label: "Privacy Focus", value: "Encrypted Intake" },
      { label: "Appointment Flow", value: "Frictionless" },
    ],
    overviewTitle: "Patient-First Healthcare Websites Built for Trust & Accessibility",
    overviewDescription: "Patients seeking medical care require clarity, comfort, and effortless navigation. We build accessible, fast-loading medical practice websites that highlight physician qualifications, clearly explain treatments, and provide secure appointment inquiry forms.",
    overviewCards: [
      {
        title: "Doctor & Specialist Profiles",
        description: "Professional physician biographies, medical board certifications, clinical specialties, and patient reviews.",
        badge: "Credentials",
        points: ["Board certifications", "Specialty filters", "Physician headshots"],
      },
      {
        title: "Online Appointment Intake",
        description: "Frictionless appointment request forms with specialty selection, preferred timing, and contact validation.",
        badge: "Appointments",
        points: ["Department selection", "Preferred time slots", "Encrypted transmission"],
      },
      {
        title: "Accessibility & Clear Typography",
        description: "High-contrast text, clear font scaling, and screen-reader accessibility ensuring all patients can navigate easily.",
        badge: "Accessibility",
        points: ["WCAG 2.1 AA targets", "High-contrast mode", "Keyboard accessible"],
      },
    ],
    capabilitiesTitle: "Healthcare Features",
    capabilitiesSubtitle: "Clinic Toolkit",
    capabilities: [
      {
        title: "Clinic Locations & Emergency Info",
        description: "Clear display of clinic hours, parking instructions, and emergency contact phone lines.",
        badge: "Locations",
        points: ["Interactive clinic map", "Direct emergency dial", "Operating hours status"],
      },
      {
        title: "Medical Organization Schema",
        description: "Structured MedicalOrganization and Physician schema for high trust and visibility on Google.",
        badge: "Medical SEO",
        points: ["Physician schema", "Medical specialties", "Location metadata"],
      },
      {
        title: "Patient FAQs & Preparation Guides",
        description: "Clear pre-visit preparation instructions and answers to common insurance and billing questions.",
        badge: "Patient FAQ",
        points: ["Insurance coverage list", "Pre-visit instructions", "Billing clarity"],
      },
    ],
    faqs: [
      {
        question: "Do your healthcare websites comply with medical advertising standards?",
        answer: "Yes. We avoid unsupported medical claims and adhere strictly to factual, professional healthcare communication standards.",
      },
    ],
    relatedLinks: [
      {
        title: "Professional Services",
        description: "Explore professional services website solutions.",
        href: "/industries/professional-services",
        category: "Industries",
      },
      {
        title: "Website Development",
        description: "Full-stack web engineering services.",
        href: "/services/website-development",
        category: "Services",
      },
      {
        title: "Pricing",
        description: "Transparent $1,000 package tiers.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Build your healthcare website.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/industries/education": {
    slug: "/industries/education",
    category: "Industries • Academics",
    title: "Education Website Development | Academic & Course Sites by Navya",
    h1: "Education Website Development",
    primaryKeyword: "education website development",
    metaDescription: "Modern website development for educational institutions, academies, and course creators by Navya Tech Industry. Course catalogs, student enrollment, and fast speeds.",
    breadcrumbs: [{ label: "Industries", href: "/industries" }, { label: "Education" }],
    heroDescription: "Inspire students and simplify admissions. We build modern, accessible educational websites featuring interactive course catalogs and frictionless enrollment.",
    heroImageAlt: "Education Website Development",
    heroImageSrc: "/ai3.png",
    heroStats: [
      { label: "Course Catalogs", value: "Interactive" },
      { label: "Admissions Flow", value: "Frictionless" },
      { label: "Mobile Speed", value: "Sub-Second" },
    ],
    overviewTitle: "Empowering Learning Communities with Modern Web Architecture",
    overviewDescription: "Educational institutions, training academies, and online educators need websites that convey academic rigor while making course exploration and student enrollment intuitive across all devices.",
    overviewCards: [
      {
        title: "Interactive Course Catalogs",
        description: "Filterable curriculum catalogs with syllabus overviews, instructor bios, prerequisites, and schedules.",
        badge: "Curriculum",
        points: ["Category & skill filters", "Detailed syllabus breakdown", "Instructor credentials"],
      },
      {
        title: "Student Enrollment Funnels",
        description: "Multi-step admissions application forms with document upload capabilities and instant confirmation.",
        badge: "Enrollment",
        points: ["Online application intake", "Prerequisite validation", "Automated email updates"],
      },
      {
        title: "Campus & Faculty Showcases",
        description: "Photo galleries, campus tour videos, and faculty research publication showcases.",
        badge: "Campus",
        points: ["Faculty directories", "Event calendars", "Virtual campus tour"],
      },
    ],
    capabilitiesTitle: "Educational Capabilities",
    capabilitiesSubtitle: "Academic Systems",
    capabilities: [
      {
        title: "Course Schema Markup",
        description: "Course structured data displaying dates, prerequisites, and fees directly on Google search.",
        badge: "Course SEO",
        points: ["Course JSON-LD", "EducationalOrganization markup", "High search visibility"],
      },
      {
        title: "Navya AI Admissions Assistant",
        description: "Answers prospective student questions about tuition, schedules, and application deadlines 24/7.",
        badge: "Admissions Bot",
        points: ["24/7 student guidance", "Application deadline reminders", "Lead capture"],
      },
      {
        title: "Student Testimonials & Alumni Outcomes",
        description: "Alumni success stories, career placement statistics, and video testimonials.",
        badge: "Alumni Proof",
        points: ["Career outcome metrics", "Alumni spotlights", "Hiring partner logos"],
      },
    ],
    faqs: [
      {
        question: "Can Navya integrate with our existing Learning Management System (LMS)?",
        answer: "Yes, we can link your marketing website directly to Canvas, Moodle, Teachable, or custom LMS student portals.",
      },
    ],
    relatedLinks: [
      {
        title: "Services Ecosystem",
        description: "Explore all Navya development services.",
        href: "/services",
        category: "Services",
      },
      {
        title: "Pricing Matrix",
        description: "Explore transparent package options.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Build your education website.",
        href: "/get-started",
        category: "Intake",
      },
      {
        title: "Contact Us",
        description: "Speak with our education specialists.",
        href: "/contact",
        category: "Contact",
      },
    ],
  },

  "/industries/ecommerce": {
    slug: "/industries/ecommerce",
    category: "Industries • Retail",
    title: "Ecommerce Industry Solutions | Online Store Development by Navya",
    h1: "Ecommerce Industry Solutions",
    primaryKeyword: "ecommerce website development",
    metaDescription: "High-performance online store development for direct-to-consumer and retail brands by Navya Tech Industry. Fast browsing, secure checkout, and high conversions.",
    breadcrumbs: [{ label: "Industries", href: "/industries" }, { label: "Ecommerce" }],
    heroDescription: "Turn digital window shoppers into repeat buyers with lightning-fast product catalogs, 3D visual showcases, and streamlined one-page checkout flows.",
    heroImageAlt: "Ecommerce Industry Solutions",
    heroImageSrc: "/ai4.png",
    heroStats: [
      { label: "Catalog Browsing", value: "Sub-Second" },
      { label: "Payment Gateways", value: "Stripe / Razorpay" },
      { label: "Mobile Cart UX", value: "Bottom Sheet" },
    ],
    overviewTitle: "Engineering Modern Digital Storefronts for Retail Growth",
    overviewDescription: "Modern retail brands cannot compete with slow, bloated template stores. We build bespoke Next.js ecommerce storefronts that load instantly, display rich visual details, and make purchasing completely frictionless.",
    overviewCards: [
      {
        title: "Instantaneous Product Search",
        description: "Client-side search and filtering allowing shoppers to find colors, sizes, and categories without lag.",
        badge: "Fast Search",
        points: ["Live search autocomplete", "Multi-attribute filtering", "Zero reload browsing"],
      },
      {
        title: "High-Converting Product Details",
        description: "Retina image carousels, size guides, customer review ratings, and inventory stock counters.",
        badge: "Product UX",
        points: ["Swipeable galleries", "Real-time stock indicators", "Sticky 'Add to Cart' bar"],
      },
      {
        title: "Secure Multi-Gateway Checkout",
        description: "Encrypted payment pipelines supporting credit cards, Apple Pay, Google Pay, and UPI.",
        badge: "Checkout",
        points: ["One-page checkout", "Multiple gateways", "Automated email receipts"],
      },
    ],
    capabilitiesTitle: "Retail Toolkit",
    capabilitiesSubtitle: "Commerce Inclusions",
    capabilities: [
      {
        title: "3D Product Visualizers",
        description: "Interactive 3D model viewers letting customers inspect products from all angles before buying.",
        badge: "3D Visualizer",
        points: ["Three.js / WebGL", "Material customization", "Mobile 60fps"],
      },
      {
        title: "Product Schema & Rich Snippets",
        description: "Google Product schema displaying price, availability, and review stars in search results.",
        badge: "Product SEO",
        points: ["JSON-LD Product schema", "Google Shopping ready", "High CTR"],
      },
      {
        title: "Direct WhatsApp Inquiries",
        description: "WhatsApp shopping trigger allowing customers to inquire directly about bulk orders or customizations.",
        badge: "WhatsApp",
        points: ["Pre-filled cart text", "Instant support", "Higher conversion"],
      },
    ],
    faqs: [
      {
        question: "How do you protect ecommerce transactions and customer data?",
        answer: "All payment transactions are processed securely through PCI-DSS compliant gateways like Stripe or Razorpay with full end-to-end SSL encryption.",
      },
    ],
    relatedLinks: [
      {
        title: "Ecommerce Services",
        description: "Explore our ecommerce website engineering services.",
        href: "/services/ecommerce-website-development",
        category: "Services",
      },
      {
        title: "Ecommerce Pricing",
        description: "View packages for online stores.",
        href: "/pricing/ecommerce",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Launch your online store.",
        href: "/get-started",
        category: "Intake",
      },
      {
        title: "Pricing Matrix",
        description: "Compare commercial packages.",
        href: "/pricing",
        category: "Pricing",
      },
    ],
  },

  "/industries/technology": {
    slug: "/industries/technology",
    category: "Industries • Deep Tech",
    title: "Technology Company Website Development | Deep Tech Sites by Navya",
    h1: "Technology Company Website Development",
    primaryKeyword: "technology company website development",
    metaDescription: "Authoritative website development for tech companies, AI labs, and developer infrastructure by Navya Tech Industry. WebGL shaders, speed, and precision.",
    breadcrumbs: [{ label: "Industries", href: "/industries" }, { label: "Technology" }],
    heroDescription: "Match your company's technical sophistication with a high-performance, dark-aesthetic website powered by Next.js, WebGL shaders, and sub-second latency.",
    heroImageAlt: "Technology Company Website Development",
    heroImageSrc: "/ai5.png",
    heroStats: [
      { label: "Tech Stack", value: "Next.js + WebGL" },
      { label: "Speed Score", value: "98-100" },
      { label: "Aesthetic", value: "Tactile Dark Mode" },
    ],
    overviewTitle: "Showcasing Deep Tech with Impeccable Digital Craftsmanship",
    overviewDescription: "Technology companies and developer tool providers are judged harshly by their audience. If your website is slow or uses generic templates, technical credibility vanishes. We build engineering-first websites that command instant respect from developers and CTOs.",
    overviewCards: [
      {
        title: "GPU-Accelerated Visual Shaders",
        description: "Procedural WebGL shaders, interactive plexus canvases, and tactile claymorphism that feel technologically advanced.",
        badge: "WebGL Shaders",
        points: ["Custom GLSL shaders", "Real-time mouse reaction", "60fps mobile execution"],
      },
      {
        title: "Technical Architecture Breakdown",
        description: "Dedicated sections for system architecture diagrams, benchmark comparisons, and security standards.",
        badge: "Architecture",
        points: ["Interactive data flow diagrams", "Benchmark performance charts", "Whitepaper downloads"],
      },
      {
        title: "Sub-Second Global Delivery",
        description: "Distributed across hundreds of global edge nodes for instant worldwide loading with zero bloat.",
        badge: "Performance",
        points: ["Edge CDN routing", "Sub-50ms latency", "Clean type-safe DOM"],
      },
    ],
    capabilitiesTitle: "Tech Company Features",
    capabilitiesSubtitle: "Deep Tech Toolkit",
    capabilities: [
      {
        title: "Code Snippets & SDK Tabs",
        description: "Interactive code tabs highlighting Python, TypeScript, Go, and cURL implementation examples.",
        badge: "SDK Tabs",
        points: ["Syntax highlighting", "One-click copy button", "Multi-language support"],
      },
      {
        title: "Security & Zero-Trust Badges",
        description: "Prominently display SOC2 readiness, ISO certifications, and encryption protocols to enterprise buyers.",
        badge: "Security",
        points: ["Zero-trust principles", "Audit readiness badge", "Compliance disclosures"],
      },
      {
        title: "Integrated AI Agent Suite",
        description: "Connect autonomous AI agents to qualify incoming enterprise leads and answer technical documentation questions.",
        badge: "AI Agents",
        points: ["Automated lead triage", "Documentation search", "Instant Slack alert"],
      },
    ],
    faqs: [
      {
        question: "Can you display complex architecture diagrams and technical documentation?",
        answer: "Yes! We specialize in structuring clear technical diagrams, API reference tables, and interactive benchmark charts.",
      },
    ],
    relatedLinks: [
      {
        title: "3D Website Development",
        description: "Explore 3D and WebGL web systems.",
        href: "/services/3d-website-development",
        category: "Services",
      },
      {
        title: "SaaS Industry Solutions",
        description: "Explore SaaS platform development.",
        href: "/industries/saas",
        category: "Industries",
      },
      {
        title: "Pricing Matrix",
        description: "View our fixed commercial packages.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Build your technology website.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/industries/professional-services": {
    slug: "/industries/professional-services",
    category: "Industries • Corporate Services",
    title: "Professional Services Website Development | Legal, Accounting & Agency Sites",
    h1: "Professional Services Website Development",
    primaryKeyword: "professional services website development",
    metaDescription: "High-trust website development for legal firms, accounting practices, and agencies by Navya Tech Industry. Fast contact actions, credibility, and authority.",
    breadcrumbs: [{ label: "Industries", href: "/industries" }, { label: "Professional Services" }],
    heroDescription: "Establish market leadership for your legal, accounting, or advisory firm with an authoritative, high-converting digital presence built for client trust.",
    heroImageAlt: "Professional Services Website Development",
    heroImageSrc: "/ai1.png",
    heroStats: [
      { label: "Trust Architecture", value: "Executive" },
      { label: "Contact Flow", value: "Instant Call / Form" },
      { label: "Security Standard", value: "Encrypted" },
    ],
    overviewTitle: "Building Trust & Generating High-Value Client Inquiries",
    overviewDescription: "For law firms, CPA practices, and specialized agencies, client relationships begin with trust. We engineer professional websites that clearly explain service areas, highlight attorney and partner credentials, and provide frictionless confidential consultation booking.",
    overviewCards: [
      {
        title: "Practice Area & Service Grids",
        description: "Clear, structured categorization of practice areas with concise explanations of how you solve client challenges.",
        badge: "Practice Areas",
        points: ["Detailed service pages", "Clear scope definitions", "Direct partner routing"],
      },
      {
        title: "Partner & Team Directories",
        description: "Distinguished partner profiles highlighting education, bar admissions, published articles, and case results.",
        badge: "Leadership",
        points: ["Executive headshots", "Bar / CPA credentials", "Direct email / phone links"],
      },
      {
        title: "Confidential Inquiry Capture",
        description: "Encrypted consultation request forms and direct phone triggers (+91 93554 12903) for immediate client contact.",
        badge: "Inquiries",
        points: ["Encrypted form intake", "Direct phone dial", "WhatsApp private chat"],
      },
    ],
    capabilitiesTitle: "Firm Capabilities",
    capabilitiesSubtitle: "Professional Toolkit",
    capabilities: [
      {
        title: "Transparent Commercial Packages",
        description: "Clearly defined fixed fee packages or hourly retainer structures that eliminate billing ambiguity.",
        badge: "Fee Transparency",
        points: ["Clear scope matrix", "Retainer options", "Fixed package options"],
      },
      {
        title: "Legal & Professional Schema",
        description: "Structured LegalService and AccountingService schema for dominant Google search rankings.",
        badge: "Professional SEO",
        points: ["LegalService schema", "Address & phone metadata", "High local placement"],
      },
      {
        title: "Navya AI Assistant",
        description: "Answers basic practice questions and captures confidential client consultation details 24/7.",
        badge: "AI Assistant",
        points: ["24/7 client intake", "Instant email alerts", "Always professional"],
      },
    ],
    faqs: [
      {
        question: "Can we include legal disclaimers and terms of service seamlessly?",
        answer: "Yes, we integrate prominent disclaimers, privacy policies, and terms of engagement modals that comply with professional standards.",
      },
    ],
    relatedLinks: [
      {
        title: "Business Website",
        description: "Explore our commercial business web package.",
        href: "/business-website",
        category: "Commercial",
      },
      {
        title: "Consulting Solutions",
        description: "Explore consulting website development.",
        href: "/industries/consulting",
        category: "Industries",
      },
      {
        title: "Pricing Plans",
        description: "Transparent $1,000 package tiers.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Build your firm's website.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },
};
