import { SubpageConfig } from "@/components/templates/GenericSubpage";

export const pricingPages: Record<string, SubpageConfig> = {
  "/pricing": {
    slug: "/pricing",
    category: "Transparent Pricing",
    title: "Pricing | Fixed Commercial Web & AI Packages by Navya",
    h1: "Packages & Pricing",
    primaryKeyword: "website pricing packages",
    metaDescription: "Transparent, fixed commercial pricing for websites and AI agent automation. $1,000 Website Package, $1,000 AI Agent Package, and $1,500 Full Ecosystem Bundle.",
    breadcrumbs: [{ label: "Pricing" }],
    heroDescription: "Predictable, transparent commercial pricing. Zero hidden fees, zero recurring builder lock-ins, and 100% lifetime source code ownership.",
    heroImageAlt: "Packages and Pricing",
    heroImageSrc: "/ai2.png",
    heroStats: [
      { label: "Website Package", value: "$1,000" },
      { label: "AI Agents Package", value: "$1,000" },
      { label: "Full Ecosystem", value: "$1,500" },
    ],
    overviewTitle: "No Surprises. No Hourly Runaways. 100% Fixed Deliverables.",
    overviewDescription: "We believe in radical pricing transparency. Traditional agencies hide behind vague hourly rates that spiral out of control. At Navya, you make a fixed, milestone-backed investment and receive a complete, production-ready digital asset.",
    overviewCards: [
      {
        title: "Website Package — $1,000 / ₹79,000",
        description: "Complete modern digital presence built with Next.js, 3D WebGL interactions, responsive design systems, and lifetime source ownership.",
        badge: "$1,000 One-Time",
        points: ["Next.js & TypeScript codebase", "3D WebGL / Spline shaders", "Technical SEO & Schema", "Full GitHub repository rights"],
      },
      {
        title: "AI Agents Package — $1,000 / ₹79,000",
        description: "Autonomous multi-agent pipeline designed to automate repetitive business tasks, qualify inbound leads, and sync CRM records 24/7.",
        badge: "$1,000 One-Time",
        points: ["Autonomous agent orchestrator", "CRM & WhatsApp integrations", "Zero-drift pipeline", "Human-in-the-loop controls"],
      },
      {
        title: "Full Ecosystem Bundle — $1,500 / ₹1,19,000",
        description: "The complete Navya technological infrastructure. Combine our premier website package and AI agent automation suite together and save $500.",
        badge: "Best Value • $1,500",
        points: ["Everything in Website Package", "Everything in AI Agents Package", "Priority engineering queue", "Save $500 / ₹39,000"],
      },
    ],
    capabilitiesTitle: "What is Included in Every Package",
    capabilitiesSubtitle: "The Navya Guarantee",
    capabilities: [
      {
        title: "100% Full Source Code Ownership",
        description: "You receive clean, documented source code with zero vendor lock-in. Host anywhere you choose.",
        badge: "Ownership",
        points: ["GitHub repo handover", "Zero recurring builder tax", "Deploy anywhere"],
      },
      {
        title: "Sub-Second Performance & SEO",
        description: "Guaranteed 95+ Lighthouse scores, sub-second Core Web Vitals, and structured JSON-LD schema.",
        badge: "Performance",
        points: ["Lighthouse 95+", "Structured schema", "Global edge caching"],
      },
      {
        title: "Maintenance at $50 / Request",
        description: "Need updates down the road? Our flexible on-demand maintenance is just $50 / ₹3,900 per request with zero forced retainers.",
        badge: "Maintenance",
        points: ["$50 / change request", "No monthly lock-in", "24-hour turnaround"],
      },
    ],
    faqs: [
      {
        question: "How do payments work for our projects?",
        answer: "We operate on clear milestone billing: 50% upon project kickoff and architecture blueprint approval, and 50% upon final verification and production launch.",
      },
      {
        question: "Do you accept payments in both USD ($) and INR (₹)?",
        answer: "Yes! We support global clients in USD ($) via Stripe/Wire transfer, and clients in India in INR (₹) via Razorpay/UPI/Bank Transfer.",
      },
    ],
    relatedLinks: [
      {
        title: "India Pricing (INR)",
        description: "View pricing packages in Indian Rupees (₹).",
        href: "/pricing/india",
        category: "Pricing",
      },
      {
        title: "USA Pricing (USD)",
        description: "View pricing packages in US Dollars ($).",
        href: "/pricing/usa",
        category: "Pricing",
      },
      {
        title: "Business Website Pricing",
        description: "View business website tier details.",
        href: "/pricing/business-website",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Select your plan and start today.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/pricing/india": {
    slug: "/pricing/india",
    category: "Pricing • India",
    title: "India Pricing | Fixed INR Packages by Navya Tech Industry",
    h1: "India Pricing (INR ₹)",
    primaryKeyword: "website development pricing india",
    metaDescription: "Transparent website and AI agent pricing in India (INR). ₹79,000 Website Package, ₹79,000 AI Agents, and ₹1,19,000 Full Ecosystem Bundle by Navya.",
    breadcrumbs: [{ label: "Pricing", href: "/pricing" }, { label: "India" }],
    heroDescription: "Transparent Indian pricing in INR (₹). Built specifically for Indian founders, businesses, and enterprises looking for world-class web engineering.",
    heroImageAlt: "India Pricing Packages",
    heroImageSrc: "/ai3.png",
    heroStats: [
      { label: "Website Package", value: "₹79,000" },
      { label: "AI Agents Package", value: "₹79,000" },
      { label: "Full Ecosystem", value: "₹1,19,000" },
    ],
    overviewTitle: "World-Class Tech Engineering at Transparent Indian Rates",
    overviewDescription: "We provide Indian businesses with the exact same enterprise-grade Next.js, WebGL, and AI agent architectures we build for global tech firms—priced transparently in Indian Rupees (₹) with full GST invoicing and local payment support (UPI, Netbanking, Cards).",
    overviewCards: [
      {
        title: "Website Package — ₹79,000",
        description: "Complete modern digital web platform with Next.js, 3D WebGL shaders, mobile responsiveness, and lifetime source ownership.",
        badge: "₹79,000 One-Time",
        points: ["Next.js & TypeScript build", "WhatsApp direct integration", "Local SEO & Schema", "Complete GitHub source handover"],
      },
      {
        title: "AI Agents Package — ₹79,000",
        description: "Autonomous multi-agent pipeline designed to automate WhatsApp customer inquiries, qualify inbound leads, and sync CRM records 24/7.",
        badge: "₹79,000 One-Time",
        points: ["WhatsApp & CRM integration", "Autonomous lead qualification", "24/7 automated assistant", "Human-in-the-loop controls"],
      },
      {
        title: "Full Ecosystem Bundle — ₹1,19,000",
        description: "Complete technological package. Get both the premier website package and AI agent automation suite together and save ₹39,000.",
        badge: "Save ₹39,000",
        points: ["Complete Website Package", "Complete AI Agents Package", "Priority development queue", "Dedicated engineer access"],
      },
    ],
    capabilitiesTitle: "India Invoicing & Maintenance Standards",
    capabilitiesSubtitle: "Local Convenience",
    capabilities: [
      {
        title: "GST Invoice & Local Payments",
        description: "Seamless payments via UPI, IMPS/NEFT, Credit Cards, and GST tax input invoices provided.",
        badge: "GST Invoicing",
        points: ["GST input credit", "UPI & Netbanking", "Milestone payments (50/50)"],
      },
      {
        title: "Maintenance at ₹3,900 / Request",
        description: "On-demand updates at ₹3,900 per change request with no mandatory monthly contracts.",
        badge: "₹3,900 / Req",
        points: ["No monthly retainers", "Under 24h turnaround", "Direct phone access"],
      },
      {
        title: "Direct Indian Phone Line",
        description: "Speak directly with our senior engineering team in India at +91 93554 12903.",
        badge: "+91 93554 12903",
        points: ["Direct call support", "WhatsApp chat access", "IST working hours"],
      },
    ],
    faqs: [
      {
        question: "How do milestone payments work for Indian clients?",
        answer: "We take 50% advance upon project initiation and requirement signoff, and the remaining 50% upon complete staging preview verification and live deployment.",
      },
    ],
    relatedLinks: [
      {
        title: "Global Pricing",
        description: "Explore our global pricing overview.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "USA Pricing (USD)",
        description: "View pricing packages in US Dollars.",
        href: "/pricing/usa",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Start your project inquiry.",
        href: "/get-started",
        category: "Intake",
      },
      {
        title: "Contact Us",
        description: "Call +91 93554 12903.",
        href: "/contact",
        category: "Contact",
      },
    ],
  },

  "/pricing/usa": {
    slug: "/pricing/usa",
    category: "Pricing • USA & Global",
    title: "USA Pricing | Fixed USD Packages by Navya Tech Industry",
    h1: "USA & Global Pricing (USD $)",
    primaryKeyword: "website development pricing usa",
    metaDescription: "Fixed website development and AI automation pricing in USD ($). $1,000 Website Package, $1,000 AI Agents, and $1,500 Full Ecosystem Bundle by Navya.",
    breadcrumbs: [{ label: "Pricing", href: "/pricing" }, { label: "USA" }],
    heroDescription: "Transparent USD ($) pricing for US and international enterprises. Fixed deliverables, zero surprise agency invoices, and 100% full source ownership.",
    heroImageAlt: "USA Pricing Packages",
    heroImageSrc: "/ai4.png",
    heroStats: [
      { label: "Website Package", value: "$1,000" },
      { label: "AI Agents Package", value: "$1,000" },
      { label: "Full Ecosystem", value: "$1,500" },
    ],
    overviewTitle: "Fixed-Fee Web & AI Engineering for US Companies",
    overviewDescription: "US agencies routinely bill $10,000 to $30,000 for standard websites with endless hourly scope creep. Navya provides senior-level engineering, bespoke design, and 3D WebGL visual accents for a transparent, fixed investment of $1,000.",
    overviewCards: [
      {
        title: "Website Package — $1,000",
        description: "Complete modern digital presence built with Next.js, 3D WebGL interactions, responsive design systems, and full GitHub source handover.",
        badge: "$1,000 Fixed",
        points: ["Next.js & TypeScript codebase", "3D WebGL / Spline shaders", "Technical SEO & Schema", "Lifetime source code rights"],
      },
      {
        title: "AI Agents Package — $1,000",
        description: "Autonomous multi-agent pipeline designed to automate repetitive tasks, qualify inbound leads, and sync CRM records 24/7.",
        badge: "$1,000 Fixed",
        points: ["Autonomous agent orchestrator", "CRM & lead sync tools", "Zero-drift pipeline", "Human-in-the-loop controls"],
      },
      {
        title: "Full Ecosystem Bundle — $1,500",
        description: "The complete Navya technological infrastructure. Combine our premier website package and AI agent automation suite together and save $500.",
        badge: "Save $500",
        points: ["Everything in Website Package", "Everything in AI Agents Package", "Priority engineering queue", "Zero recurring builder fees"],
      },
    ],
    capabilitiesTitle: "US Commercial Standards",
    capabilitiesSubtitle: "Inclusions",
    capabilities: [
      {
        title: "Stripe & Wire Invoicing",
        description: "Pay securely via Stripe (Credit Card, Apple Pay) or direct ACH / Wire transfer in USD.",
        badge: "Stripe & Wire",
        points: ["Instant Stripe receipts", "ACH / Wire transfer", "Milestone billing (50/50)"],
      },
      {
        title: "Maintenance at $50 / Request",
        description: "On-demand maintenance at $50 per change request with zero required retainers.",
        badge: "$50 / Req",
        points: ["No monthly lock-in", "Under 24h turnaround", "Senior engineer execution"],
      },
      {
        title: "US Timezone Support",
        description: "Seamless collaboration aligned with Eastern, Central, and Pacific working hours.",
        badge: "Global Timezones",
        points: ["Daily async updates", "Slack / Email sync", "Rapid response times"],
      },
    ],
    faqs: [
      {
        question: "How do payments work for US companies?",
        answer: "We invoice via Stripe in USD ($) or direct wire. 50% is billed upon project kickoff and 50% upon production deployment.",
      },
    ],
    relatedLinks: [
      {
        title: "Global Pricing",
        description: "View our global pricing matrix.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "India Pricing (INR)",
        description: "View pricing packages in Indian Rupees.",
        href: "/pricing/india",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Start your project intake.",
        href: "/get-started",
        category: "Intake",
      },
      {
        title: "Book a Call",
        description: "Schedule a consultation.",
        href: "/book-a-call",
        category: "Contact",
      },
    ],
  },

  "/pricing/business-website": {
    slug: "/pricing/business-website",
    category: "Pricing • Corporate",
    title: "Business Website Pricing | Corporate Web Packages by Navya",
    h1: "Business Website Pricing",
    primaryKeyword: "business website pricing",
    metaDescription: "Explore business website pricing and packages by Navya Tech Industry. Complete $1,000 corporate website solution with lead generation, SEO, and full source code.",
    breadcrumbs: [{ label: "Pricing", href: "/pricing" }, { label: "Business Website" }],
    heroDescription: "Transparent corporate packages engineered to establish authority, generate qualified inbound inquiries, and deliver measurable business ROI.",
    heroImageAlt: "Business Website Pricing",
    heroImageSrc: "/ai5.png",
    heroStats: [
      { label: "Corporate Package", value: "$1,000 / ₹10k" },
      { label: "Turnaround Time", value: "7-14 Days" },
      { label: "Builder Subscriptions", value: "$0 Never" },
    ],
    overviewTitle: "Everything Your Business Needs to Win Online",
    overviewDescription: "We designed our business website package to give growing companies and established firms an enterprise-grade digital asset without the bloated price tag of legacy agencies. One flat fee covers architecture, design, development, SEO, and global deployment.",
    overviewCards: [
      {
        title: "Corporate Visual Authority",
        description: "Bespoke design system with claymorphic elevation, executive typography, and structured proof sections.",
        badge: "Design",
        points: ["Custom UI design tokens", "Dark/light mode support", "High-contrast accessibility"],
      },
      {
        title: "Multi-Channel Inbound Funnels",
        description: "One-tap phone calls (+91 93554 12903), WhatsApp direct chat, and interactive project inquiry forms.",
        badge: "Leads",
        points: ["Direct click-to-call", "Instant WhatsApp routing", "Interactive quote intake"],
      },
      {
        title: "Search & Local SEO Foundations",
        description: "Organization structured data, dynamic OpenGraph social share cards, and clean canonical hierarchy.",
        badge: "SEO",
        points: ["Organization schema", "Google Maps integration", "XML sitemaps"],
      },
    ],
    capabilitiesTitle: "Corporate Package Inclusions",
    capabilitiesSubtitle: "Complete Deliverables",
    capabilities: [
      {
        title: "Navya AI Assistant Integration",
        description: "Autonomous chatbot answering client questions and routing qualified leads 24/7.",
        badge: "AI Assistant",
        points: ["24/7 client answers", "Automated email alerts", "Always online"],
      },
      {
        title: "Full GitHub Code Handover",
        description: "100% full source ownership with zero recurring website builder license fees.",
        badge: "Ownership",
        points: ["GitHub repo transfer", "Zero builder taxes", "Deploy anywhere"],
      },
      {
        title: "Post-Launch Warranty",
        description: "Dedicated 30-day warranty ensuring flawless performance under real customer traffic.",
        badge: "Warranty",
        points: ["Bug fixes included", "Performance monitoring", "Direct engineer access"],
      },
    ],
    faqs: [
      {
        question: "Can we add more pages or custom integrations to our business website later?",
        answer: "Yes! Because our architecture is 100% modular Next.js, adding new service pages or custom portals down the road is simple and cost-effective.",
      },
    ],
    relatedLinks: [
      {
        title: "Business Website Overview",
        description: "Explore our commercial business website features.",
        href: "/business-website",
        category: "Commercial",
      },
      {
        title: "3D Website Pricing",
        description: "View pricing packages for 3D web experiences.",
        href: "/pricing/3d-website",
        category: "Pricing",
      },
      {
        title: "Pricing Matrix",
        description: "View all commercial package options.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Start your business website build.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/pricing/3d-website": {
    slug: "/pricing/3d-website",
    category: "Pricing • Immersive",
    title: "3D Website Pricing | WebGL & Three.js Packages by Navya",
    h1: "3D Website Pricing",
    primaryKeyword: "3d website pricing",
    metaDescription: "Transparent pricing for 3D and WebGL websites by Navya Tech Industry. GPU-accelerated shaders, Three.js viewports, and 60fps performance starting at $1,000.",
    breadcrumbs: [{ label: "Pricing", href: "/pricing" }, { label: "3D Website" }],
    heroDescription: "Affordable, fixed pricing for high-performance 3D websites, WebGL shader engines, and interactive Three.js product visualizers.",
    heroImageAlt: "3D Website Pricing",
    heroImageSrc: "/ai1.png",
    heroStats: [
      { label: "3D Web Package", value: "$1,000 / ₹10k" },
      { label: "Performance", value: "60 FPS Guarantee" },
      { label: "Lighthouse Score", value: "95+ Maintained" },
    ],
    overviewTitle: "Immersive 3D Experiences at Fixed Commercial Rates",
    overviewDescription: "3D websites used to require $50,000+ budgets and specialized creative studios. Navya democratizes immersive 3D web engineering by providing production Three.js scenes, procedural GLSL shaders, and interactive models at accessible, fixed commercial pricing.",
    overviewCards: [
      {
        title: "GPU-Accelerated WebGL Shaders",
        description: "Custom procedural shaders and interactive background canvases running at a silky 60fps with zero CPU lag.",
        badge: "WebGL",
        points: ["Custom GLSL shaders", "Real-time mouse reactivity", "Dynamic LOD scaling"],
      },
      {
        title: "Interactive 3D Viewports",
        description: "3D product visualizers, interactive machinery models, and smooth camera path keyframes.",
        badge: "Three.js",
        points: ["React Three Fiber", "Orbit and pan controls", "Optimized mesh geometry"],
      },
      {
        title: "Performance & SEO Safe",
        description: "Non-blocking canvas layers ensure your Core Web Vitals and Google search rankings remain flawless.",
        badge: "Performance",
        points: ["Sub-second LCP", "Non-blocking DOM", "Full source rights"],
      },
    ],
    capabilitiesTitle: "3D Package Inclusions",
    capabilitiesSubtitle: "WebGL Standards",
    capabilities: [
      {
        title: "Spline 3D Scene Integration",
        description: "Lightweight Spline runtime embedding with interactive state triggers and hover transitions.",
        badge: "Spline",
        points: ["State triggers", "Smooth camera animations", "Asset compression"],
      },
      {
        title: "Mobile Adaptive Performance",
        description: "Hardware-detected particle scaling ensuring smooth 60fps execution on phones and tablets.",
        badge: "Mobile 60fps",
        points: ["Device detection", "Battery-friendly shaders", "Adaptive resolution"],
      },
      {
        title: "100% Full Source Handover",
        description: "Complete GitHub repository handover with full rights to all 3D assets and shaders.",
        badge: "Ownership",
        points: ["Full GitHub transfer", "No licensing fees", "Deploy anywhere"],
      },
    ],
    faqs: [
      {
        question: "Can we supply our own 3D CAD or GLTF models?",
        answer: "Yes! We can import and optimize your existing 3D models (GLTF, GLB, OBJ, FBX) or build custom procedural scenes from scratch.",
      },
    ],
    relatedLinks: [
      {
        title: "3D Website Overview",
        description: "Explore our 3D web capabilities.",
        href: "/3d-website",
        category: "Commercial",
      },
      {
        title: "3D Website Development",
        description: "Explore 3D web engineering services.",
        href: "/services/3d-website-development",
        category: "Services",
      },
      {
        title: "Global Pricing",
        description: "View all commercial package options.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Discuss your 3D project.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/pricing/ecommerce": {
    slug: "/pricing/ecommerce",
    category: "Pricing • Retail",
    title: "Ecommerce Website Pricing | Online Store Packages by Navya",
    h1: "Ecommerce Website Pricing",
    primaryKeyword: "ecommerce website pricing",
    metaDescription: "Transparent ecommerce website pricing by Navya Tech Industry. Complete digital storefront packages, secure payments, and high-converting product pages.",
    breadcrumbs: [{ label: "Pricing", href: "/pricing" }, { label: "Ecommerce" }],
    heroDescription: "Fixed-price ecommerce website packages engineered for high product catalog speeds, frictionless checkout, and high conversion rates.",
    heroImageAlt: "Ecommerce Website Pricing",
    heroImageSrc: "/ai2.png",
    heroStats: [
      { label: "Store Package", value: "$1,000 / ₹10k" },
      { label: "Monthly Platform Cut", value: "0% Zero" },
      { label: "Gateways", value: "Stripe & Razorpay" },
    ],
    overviewTitle: "A High-Converting Online Store You Truly Own",
    overviewDescription: "Tired of paying monthly subscription fees and transaction percentages to closed ecommerce platforms? Navya builds bespoke, high-speed Next.js digital storefronts that you own 100% outright with zero platform commission fees.",
    overviewCards: [
      {
        title: "Fast Catalog Browsing",
        description: "Instant product filtering, category search, and product detail viewports that load without page refreshes.",
        badge: "Catalog",
        points: ["Instant client filtering", "Responsive image galleries", "Stock inventory indicators"],
      },
      {
        title: "Frictionless Checkout",
        description: "One-page checkout flows with Apple Pay, Google Pay, credit cards, and UPI integration.",
        badge: "Checkout",
        points: ["One-page checkout", "Multiple payment gateways", "Automated email receipts"],
      },
      {
        title: "0% Commission Platform Fees",
        description: "Keep 100% of your product revenue. You only pay standard gateway fees with zero platform markup from us.",
        badge: "0% Commission",
        points: ["Zero platform tax", "Direct gateway deposits", "100% full ownership"],
      },
    ],
    capabilitiesTitle: "Ecommerce Package Inclusions",
    capabilitiesSubtitle: "Store Toolkit",
    capabilities: [
      {
        title: "Product Schema & Rich Snippets",
        description: "Google Product schema displaying pricing, availability, and star ratings on Google search.",
        badge: "Product SEO",
        points: ["Product JSON-LD schema", "Google Shopping ready", "High CTR"],
      },
      {
        title: "Mobile Cart Drawer & Sticky CTA",
        description: "Smooth bottom-sheet cart drawers and sticky 'Buy Now' buttons optimized for mobile thumbs.",
        badge: "Mobile UX",
        points: ["Sticky mobile checkout", "Swipeable galleries", "Touch-friendly inputs"],
      },
      {
        title: "Direct WhatsApp Orders",
        description: "WhatsApp shopping trigger allowing customers to send orders directly with pre-formatted item lists.",
        badge: "WhatsApp",
        points: ["Pre-filled cart text", "Instant support", "Higher conversion"],
      },
    ],
    faqs: [
      {
        question: "Can we integrate with shipping carriers and automated tracking?",
        answer: "Yes! We can configure webhooks for automated shipping label generation and customer tracking number notifications.",
      },
    ],
    relatedLinks: [
      {
        title: "Ecommerce Services",
        description: "Explore our ecommerce website development services.",
        href: "/services/ecommerce-website-development",
        category: "Services",
      },
      {
        title: "Ecommerce Industries",
        description: "Explore dedicated retail solutions.",
        href: "/industries/ecommerce",
        category: "Industries",
      },
      {
        title: "Pricing Matrix",
        description: "Compare all commercial packages.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Launch your ecommerce store.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },
};
