import { SubpageConfig } from "@/components/templates/GenericSubpage";

export const servicePages: Record<string, SubpageConfig> = {
  "/services": {
    slug: "/services",
    category: "Service Ecosystem",
    title: "Services | Complete Digital Engineering & AI Ecosystem by Navya",
    h1: "Services Ecosystem",
    primaryKeyword: "website development services",
    metaDescription: "Explore Navya Tech Industry's complete service ecosystem: full-stack web engineering, 3D WebGL experiences, custom UI/UX design, SEO, and AI workflow automation.",
    breadcrumbs: [{ label: "Services" }],
    heroDescription: "An interconnected engineering and design ecosystem built to turn complex business challenges into high-performance digital systems and measurable revenue growth.",
    heroImageAlt: "Services Ecosystem",
    heroImageSrc: "/ai1.png",
    heroStats: [
      { label: "Core Service Pillars", value: "3 Pillars" },
      { label: "Engineering Disciplines", value: "12 Specializations" },
      { label: "Global Delivery", value: "Enterprise Ready" },
    ],
    overviewTitle: "A Cohesive Architecture of Digital & Automated Services",
    overviewDescription: "We do not treat services as isolated checkboxes. Every website, 3D shader, API pipeline, and AI agent we build operates as a synchronized ecosystem designed to lower operational friction, captivate visitors, and maximize lifetime customer value.",
    overviewCards: [
      {
        title: "Digital Experiences & Web Engineering",
        description: "Full-stack web applications, landing pages, 3D experiences, and corporate platforms built with Next.js and Tailwind CSS.",
        badge: "Web Engineering",
        points: ["Next.js & React 18", "WebGL / Three.js", "Core Web Vitals 95+"],
      },
      {
        title: "AI Agents & Autonomous Workflows",
        description: "Intelligent agent pipelines for lead qualification, automated communications, and seamless CRM synchronization.",
        badge: "AI Automation",
        points: ["Autonomous lead intake", "WhatsApp / CRM sync", "Zero-drift pipelines"],
      },
      {
        title: "Security & Infrastructure Systems",
        description: "Zero-trust architecture, audit readiness, edge CDN deployments, and continuous performance optimization.",
        badge: "Security",
        points: ["Threat modeling", "Cloudflare / Vercel Edge", "Automated telemetry"],
      },
    ],
    capabilitiesTitle: "Explore Our Full Range of Services",
    capabilitiesSubtitle: "Specialized Disciplines",
    capabilities: [
      {
        title: "Website Development",
        description: "Next.js frontend, type-safe backend integrations, and sub-second edge deployment.",
        badge: "/services/website-development",
        points: ["Type-safe TypeScript", "REST & GraphQL APIs", "Lighthouse 95+"],
      },
      {
        title: "Website Design & UI/UX",
        description: "Custom design systems, claymorphic lighting, and high-conversion wireframes.",
        badge: "/services/website-design",
        points: ["Design tokens", "Dark/light modes", "Micro-interactions"],
      },
      {
        title: "3D & WebGL Development",
        description: "GPU-accelerated procedural shaders and interactive 3D viewports at 60fps.",
        badge: "/services/3d-website-development",
        points: ["Three.js & Spline", "GLSL shaders", "Mobile adaptive"],
      },
      {
        title: "Custom Web Development",
        description: "Bespoke web applications, interactive calculators, and custom workflows.",
        badge: "/services/custom-web-development",
        points: ["Zero template bloat", "Custom data models", "Full source ownership"],
      },
      {
        title: "Landing Page Engineering",
        description: "Ultra high-conversion landing pages built specifically for paid ad campaigns.",
        badge: "/services/landing-page-development",
        points: ["A/B test ready", "Frictionless forms", "Sub-second load"],
      },
      {
        title: "Website Performance & CWV",
        description: "Auditing and optimizing load times, rendering pipelines, and Core Web Vitals.",
        badge: "/services/website-performance-optimization",
        points: ["LCP / INP / CLS tuning", "Asset compression", "Edge caching"],
      },
    ],
    faqs: [
      {
        question: "Can Navya combine multiple services into a single unified package?",
        answer: "Yes! Our Full Ecosystem Bundle ($1,500 / ₹1,19,000) combines full-stack website engineering with our AI agent workflow automation suite.",
      },
      {
        question: "How do we choose which service is right for our business?",
        answer: "You can book a free consultation call (+91 93554 12903) or start an inquiry on our /get-started page to receive an engineering recommendation.",
      },
    ],
    relatedLinks: [
      {
        title: "Website Development",
        description: "Full-stack web engineering services.",
        href: "/services/website-development",
        category: "Services",
      },
      {
        title: "3D Website Development",
        description: "WebGL and 3D web applications.",
        href: "/services/3d-website-development",
        category: "Services",
      },
      {
        title: "Pricing Matrix",
        description: "Explore our fixed commercial packages.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Start your project inquiry with Navya.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/services/website-development": {
    slug: "/services/website-development",
    category: "Services • Engineering",
    title: "Website Development Services | Navya Tech Industry",
    h1: "Website Development Services",
    primaryKeyword: "website development services",
    metaDescription: "Professional website development services by Navya Tech Industry. Modern Next.js frontend, type-safe TypeScript, backend integrations, and edge deployment.",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Website Development" }],
    heroDescription: "Engineered from the ground up for speed, security, accessibility, and measurable commercial results. Full-stack development that scales with your growth.",
    heroImageAlt: "Website Development Services",
    heroImageSrc: "/ai2.png",
    heroStats: [
      { label: "Frontend Speed", value: "Sub-Second" },
      { label: "Accessibility Target", value: "WCAG 2.1 AA" },
      { label: "Code Ownership", value: "100% Full" },
    ],
    overviewTitle: "Full-Stack Web Engineering for Forward-Thinking Companies",
    overviewDescription: "We engineer resilient, modern web platforms using Next.js, React 18, and TypeScript. Our architecture ensures lightning-fast page transitions, accessible semantics, search-engine visibility, and painless long-term maintainability.",
    overviewCards: [
      {
        title: "Modern Frontend Architecture",
        description: "Modular React component structures with zero bloat, type safety, and seamless dynamic state management.",
        badge: "Frontend",
        points: ["Next.js App/Pages router", "Tailwind CSS v3", "Framer Motion"],
      },
      {
        title: "Backend & Integrations",
        description: "Robust API route handlers, webhook listeners, database syncing, and payment gateway connections.",
        badge: "Backend",
        points: ["Stripe / Razorpay", "Headless CMS", "CRM webhooks"],
      },
      {
        title: "Edge Cloud Infrastructure",
        description: "Global CDN distribution with automated CI/CD pipelines, SSL automation, and real-time telemetry.",
        badge: "Cloud Edge",
        points: ["Vercel / Cloudflare Edge", "Automated previews", "99.99% uptime SLA"],
      },
    ],
    capabilitiesTitle: "Development Capabilities",
    capabilitiesSubtitle: "Full-Stack Rigor",
    capabilities: [
      {
        title: "TypeScript Precision",
        description: "Complete compile-time safety and strict interface definitions across all components.",
        badge: "TypeScript",
        points: ["Strict mode", "Zero any-types", "Reusable contracts"],
      },
      {
        title: "SEO-Ready Architecture",
        description: "Static HTML generation, automated metadata injection, canonical URLs, and schema markup.",
        badge: "SEO",
        points: ["JSON-LD Schema", "Dynamic OpenGraph", "XML Sitemap"],
      },
      {
        title: "Accessibility Standards",
        description: "Semantic HTML5, ARIA landmark compliance, keyboard focus rings, and high color contrast.",
        badge: "A11y",
        points: ["Screen reader ready", "Keyboard navigation", "Focus states"],
      },
    ],
    faqs: [
      {
        question: "Do you build backend functionality or only frontend interfaces?",
        answer: "We provide complete full-stack development, including serverless API routes, database connections (PostgreSQL/Supabase/Firebase), and third-party webhook integrations.",
      },
    ],
    relatedLinks: [
      {
        title: "Services Ecosystem",
        description: "Explore all Navya capabilities.",
        href: "/services",
        category: "Services",
      },
      {
        title: "Website Design",
        description: "Learn about our UI/UX design process.",
        href: "/services/website-design",
        category: "Services",
      },
      {
        title: "Pricing Plans",
        description: "Transparent $1,000 website package.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Initiate your development project.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/services/website-design": {
    slug: "/services/website-design",
    category: "Services • UI/UX",
    title: "Website Design Services | UI/UX & Design Systems by Navya",
    h1: "Website Design Services",
    primaryKeyword: "website design services",
    metaDescription: "Bespoke website design services by Navya Tech Industry. UI/UX design systems, claymorphic aesthetics, mobile-first responsiveness, and conversion architecture.",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Website Design" }],
    heroDescription: "Designing memorable digital interfaces that build authority, delight users, and drive consistent conversions through refined visual hierarchy and tactile claymorphism.",
    heroImageAlt: "Website Design Services",
    heroImageSrc: "/ai3.png",
    heroStats: [
      { label: "Design System", value: "Tokens & Kits" },
      { label: "UX Flow", value: "Conversion-Led" },
      { label: "Device Coverage", value: "100% Adaptive" },
    ],
    overviewTitle: "UI/UX Design Tailored for Impact & Conversion",
    overviewDescription: "Great design is not just visual ornamentation; it is the deliberate orchestration of typography, contrast, spacing, and micro-interactions to guide visitor decisions effortlessly. We engineer bespoke design systems that elevate your brand.",
    overviewCards: [
      {
        title: "User Experience (UX) Architecture",
        description: "Detailed wireframing and user journey mapping that eliminates cognitive friction and accelerates decision-making.",
        badge: "UX Strategy",
        points: ["Frictionless navigation", "Clear CTA pathways", "Information hierarchy"],
      },
      {
        title: "User Interface (UI) Craftsmanship",
        description: "Distinctive claymorphic cards, polished dark aesthetics, subtle bevel lighting, and curated typography.",
        badge: "Visual UI",
        points: ["Custom shadow tokens", "Claymorphic elevation", "Curated font pairings"],
      },
      {
        title: "Responsive Design Systems",
        description: "Fluid design tokens that adapt gracefully across mobile phones, tablets, laptops, and ultra-wide screens.",
        badge: "Responsive",
        points: ["Touch-optimized targets", "Adaptive font scaling", "Zero overflow"],
      },
    ],
    capabilitiesTitle: "Design System Deliverables",
    capabilitiesSubtitle: "Complete Assets",
    capabilities: [
      {
        title: "Figma Prototype Blueprint",
        description: "Interactive Figma components and clickable prototypes for rapid stakeholder feedback.",
        badge: "Figma",
        points: ["Component libraries", "Auto-layout frames", "Color styles"],
      },
      {
        title: "Claymorphic Component Tokens",
        description: "Pre-configured CSS tokens for shadows, borders, radiuses, and glassmorphic overlays.",
        badge: "CSS Tokens",
        points: ["Light/dark themes", "Tailwind utility config", "Accessible contrast"],
      },
      {
        title: "Micro-Interaction Motion Spec",
        description: "Specifications for hover states, scroll animations, loading skeletons, and interactive feedback.",
        badge: "Motion",
        points: ["Framer Motion presets", "Reduced motion support", "Hardware acceleration"],
      },
    ],
    faqs: [
      {
        question: "How many design concepts do you provide?",
        answer: "We deliver an initial interactive prototype and conduct iterative review cycles until the design aligns precisely with your brand standards.",
      },
    ],
    relatedLinks: [
      {
        title: "Website Development",
        description: "See our frontend engineering capabilities.",
        href: "/services/website-development",
        category: "Services",
      },
      {
        title: "3D Website Development",
        description: "Explore 3D and WebGL visual design.",
        href: "/services/3d-website-development",
        category: "Services",
      },
      {
        title: "Website Redesign",
        description: "Modernize your existing website design.",
        href: "/services/website-redesign",
        category: "Services",
      },
      {
        title: "Get Started",
        description: "Book a design consultation.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/services/3d-website-development": {
    slug: "/services/3d-website-development",
    category: "Services • Immersive Tech",
    title: "3D Website Development Services | WebGL & Three.js by Navya",
    h1: "3D Website Development Services",
    primaryKeyword: "3d website development services",
    metaDescription: "Custom 3D website development services by Navya Tech Industry. WebGL, Three.js, Spline, and custom GLSL shaders engineered for 60fps performance and fast loading.",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "3D Website Development" }],
    heroDescription: "Transform standard web pages into unforgettable immersive worlds with custom Three.js WebGL systems and procedural shaders that run at a smooth 60fps.",
    heroImageAlt: "3D Website Development Services",
    heroImageSrc: "/ai4.png",
    heroStats: [
      { label: "Frame Rate", value: "60 FPS" },
      { label: "Shader Engine", value: "Custom GLSL" },
      { label: "Lighthouse Score", value: "95+ Maintained" },
    ],
    overviewTitle: "High-Performance 3D Web Engineering for Modern Brands",
    overviewDescription: "We bridge the gap between creative 3D art and production web engineering. Our WebGL pipelines are lightweight, hardware-adaptive, and optimized for mobile devices so you get jaw-dropping visual appeal without sacrificing speed.",
    overviewCards: [
      {
        title: "Custom GLSL Shaders",
        description: "GPU-accelerated fragment and vertex shaders that produce captivating fluid motion, lighting, and tactile textures.",
        badge: "WebGL / GLSL",
        points: ["Procedural math", "Minimal CPU overhead", "Real-time mouse reactivity"],
      },
      {
        title: "Interactive 3D Viewports",
        description: "Engaging 3D product visualizers, interactive machinery models, and camera path storytelling.",
        badge: "Three.js",
        points: ["React Three Fiber", "Orbit and pan controls", "Optimized mesh geometry"],
      },
      {
        title: "Performance-Conscious Architecture",
        description: "Intelligent level-of-detail (LOD), canvas pausing when offscreen, and reduced-power mobile fallbacks.",
        badge: "Optimization",
        points: ["Intersection observer pausing", "Adaptive particle counts", "Zero main-thread jank"],
      },
    ],
    capabilitiesTitle: "3D Engineering Services",
    capabilitiesSubtitle: "Immersive Capabilities",
    capabilities: [
      {
        title: "Spline 3D Scene Integration",
        description: "Seamless embedding of lightweight Spline scenes with interactive event listeners and state transitions.",
        badge: "Spline",
        points: ["State triggers", "Smooth camera animations", "Asset compression"],
      },
      {
        title: "Plexus & Particle Dynamics",
        description: "Interactive particle networks with physics-based velocity, attraction, and repulsion dynamics.",
        badge: "Particles",
        points: ["Canvas 2D / WebGL", "Smooth velocity damping", "Zero CPU strain"],
      },
      {
        title: "3D Web Pricing & Packages",
        description: "Dedicated packages for adding immersive 3D hero sections or complete 3D websites.",
        badge: "Packages",
        points: ["Fixed pricing", "Full source transfer", "Cross-browser testing"],
      },
    ],
    faqs: [
      {
        question: "How do 3D websites perform on older phones or slow connections?",
        answer: "We implement progressive enhancement: devices with limited GPU power automatically receive a lighter shader tier or elegant CSS fallback, guaranteeing smooth browsing everywhere.",
      },
    ],
    relatedLinks: [
      {
        title: "3D Website Overview",
        description: "Explore our 3D web platform overview.",
        href: "/3d-website",
        category: "Commercial",
      },
      {
        title: "3D Website Pricing",
        description: "View pricing packages for 3D web systems.",
        href: "/pricing/3d-website",
        category: "Pricing",
      },
      {
        title: "Website Development",
        description: "Full-stack web engineering services.",
        href: "/services/website-development",
        category: "Services",
      },
      {
        title: "Get Started",
        description: "Discuss your 3D project requirements.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/services/custom-web-development": {
    slug: "/services/custom-web-development",
    category: "Services • Engineering",
    title: "Custom Web Development Services | Bespoke Engineering by Navya",
    h1: "Custom Web Development Services",
    primaryKeyword: "custom web development services",
    metaDescription: "Tailored custom web development services by Navya Tech Industry. Bespoke business workflows, complex data architectures, and 100% source code ownership.",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Custom Web Development" }],
    heroDescription: "Engineered specifically for business models that cannot be constrained by off-the-shelf templates or generic website builders.",
    heroImageAlt: "Custom Web Development Services",
    heroImageSrc: "/ai5.png",
    heroStats: [
      { label: "Bespoke Logic", value: "100% Tailored" },
      { label: "Data Integration", value: "Any API / DB" },
      { label: "Vendor Lock-in", value: "0% Zero" },
    ],
    overviewTitle: "Custom Web Applications & Specialized Business Logic",
    overviewDescription: "When your business requires custom pricing estimators, multi-step qualification pipelines, customer portals, or bespoke integrations, generic site builders fall flat. Navya architects custom web systems engineered to match your exact operational model.",
    overviewCards: [
      {
        title: "Bespoke Business Logic",
        description: "Custom interactive calculators, quoting engines, and dynamic configuration tools built into your web pages.",
        badge: "Business Logic",
        points: ["Dynamic pricing engines", "Step-by-step intake", "Real-time state validation"],
      },
      {
        title: "Secure API Architecture",
        description: "Protected serverless endpoints, authentication tokens, and webhook listeners for seamless business sync.",
        badge: "Security & APIs",
        points: ["Encrypted communication", "OAuth / JWT authentication", "Zero-trust endpoints"],
      },
      {
        title: "Long-Term Scalability",
        description: "Clean architecture that lets your team easily add new features, microservices, and databases down the road.",
        badge: "Scalability",
        points: ["Modular architecture", "Microservice compatibility", "Comprehensive documentation"],
      },
    ],
    capabilitiesTitle: "What We Engineer",
    capabilitiesSubtitle: "Custom Solutions",
    capabilities: [
      {
        title: "Custom Customer Portals",
        description: "Secure, authenticated areas for clients to view projects, invoices, or analytics.",
        badge: "Portals",
        points: ["Role-based access", "Supabase / Firebase auth", "Live dashboards"],
      },
      {
        title: "Complex Lead Qualification",
        description: "Multi-branch questionnaires that qualify leads and route data directly to sales reps.",
        badge: "Intake",
        points: ["Conditional routing", "WhatsApp notifications", "CRM push"],
      },
      {
        title: "Automated Reporting Views",
        description: "Interactive data visualization tables and charts displaying key company metrics.",
        badge: "Analytics",
        points: ["Real-time data feeds", "Export capabilities", "Responsive charts"],
      },
    ],
    faqs: [
      {
        question: "How do you estimate timelines for custom web development projects?",
        answer: "We review your requirements and provide a clear milestone roadmap. Most custom modules are completed within 2 to 4 weeks.",
      },
    ],
    relatedLinks: [
      {
        title: "Custom Website",
        description: "Explore our custom web commercial packages.",
        href: "/custom-website",
        category: "Commercial",
      },
      {
        title: "Web App Development",
        description: "Explore interactive web applications.",
        href: "/services/web-app-development",
        category: "Services",
      },
      {
        title: "Pricing",
        description: "Transparent package options.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Share your custom requirements.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/services/business-website-development": {
    slug: "/services/business-website-development",
    category: "Services • Corporate",
    title: "Business Website Development Services | Navya Tech Industry",
    h1: "Business Website Development Services",
    primaryKeyword: "business website development services",
    metaDescription: "Comprehensive business website development services. Establish authority, drive high-intent inquiries, and grow your company with Navya Tech Industry.",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Business Website Development" }],
    heroDescription: "High-converting corporate and business websites engineered for credibility, search dominance, and multi-channel lead acquisition.",
    heroImageAlt: "Business Website Development Services",
    heroImageSrc: "/ai1.png",
    heroStats: [
      { label: "Lead Capture", value: "Multi-Channel" },
      { label: "Security", value: "Zero-Trust" },
      { label: "Starting Package", value: "$1,000" },
    ],
    overviewTitle: "A Professional Digital Engine for Your Business",
    overviewDescription: "We build business websites that act as 24/7 revenue drivers. By uniting executive aesthetics with direct calling actions (+91 93554 12903), WhatsApp routing, and clear package presentations, we ensure your business converts more visitors into paying customers.",
    overviewCards: [
      {
        title: "Executive Visual Authority",
        description: "Polished design systems with claymorphic elevation and structured proof sections that immediately earn customer trust.",
        badge: "Credibility",
        points: ["Company trust indicators", "Leadership bios", "Verified testimonials"],
      },
      {
        title: "Direct Conversion Triggers",
        description: "Prominently placed click-to-call, WhatsApp chat, and interactive RFQ forms engineered for zero friction.",
        badge: "Inbound Funnels",
        points: ["One-tap calling", "WhatsApp direct link", "Spam-filtered RFQ forms"],
      },
      {
        title: "Local & National SEO Foundations",
        description: "Built-in organization schema and localized keyword targeting to ensure top placement on Google search.",
        badge: "Search Authority",
        points: ["Organization schema", "Crawl-optimized hierarchy", "High mobile page speed"],
      },
    ],
    capabilitiesTitle: "Business Website Features",
    capabilitiesSubtitle: "Growth Tools",
    capabilities: [
      {
        title: "Service & Pricing Matrices",
        description: "Transparent pricing tables and service feature cards that answer customer questions immediately.",
        badge: "Transparency",
        points: ["Clear package tiers", "Feature checklists", "Direct CTA routing"],
      },
      {
        title: "Navya AI Assistant Integration",
        description: "Autonomous chatbot answering client questions and capturing inquiries around the clock.",
        badge: "AI Assistant",
        points: ["Instant answers", "Lead qualification", "Email alerts"],
      },
      {
        title: "Full Source Ownership",
        description: "100% source code repository handover with zero recurring builder subscriptions.",
        badge: "Ownership",
        points: ["GitHub repo transfer", "Zero builder taxes", "Deploy anywhere"],
      },
    ],
    faqs: [
      {
        question: "Can you assist with domain registration and corporate email setup?",
        answer: "Yes, we handle Google Workspace / Microsoft 365 email configuration, DNS record setup, and SSL security certificate provisioning.",
      },
    ],
    relatedLinks: [
      {
        title: "Business Website Overview",
        description: "Explore our commercial business website package.",
        href: "/business-website",
        category: "Commercial",
      },
      {
        title: "Business Website Pricing",
        description: "View pricing packages for business websites.",
        href: "/pricing/business-website",
        category: "Pricing",
      },
      {
        title: "Landing Page Development",
        description: "Explore high-conversion landing page services.",
        href: "/services/landing-page-development",
        category: "Services",
      },
      {
        title: "Get Started",
        description: "Start building your business website.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/services/landing-page-development": {
    slug: "/services/landing-page-development",
    category: "Services • Conversion",
    title: "Landing Page Development Services | High-Conversion Pages by Navya",
    h1: "Landing Page Development Services",
    primaryKeyword: "landing page development services",
    metaDescription: "High-conversion landing page development by Navya Tech Industry. Sub-second load speeds, persuasive visual hierarchy, and frictionless lead capture.",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Landing Page Development" }],
    heroDescription: "Turn expensive ad clicks into measurable revenue with ultra-fast, high-converting landing pages engineered for maximum conversion velocity.",
    heroImageAlt: "Landing Page Development Services",
    heroImageSrc: "/ai2.png",
    heroStats: [
      { label: "Load Speed", value: "< 0.8s" },
      { label: "Conversion Lift", value: "High-Intent" },
      { label: "A/B Testing", value: "Supported" },
    ],
    overviewTitle: "Conversion-Engineered Landing Pages for Growth Campaigns",
    overviewDescription: "When driving paid traffic from Google Ads, Meta, or LinkedIn, every millisecond of delay and every unnecessary form field kills conversion. We build razor-sharp landing pages focused on a single commercial goal.",
    overviewCards: [
      {
        title: "Sub-Second Page Loads",
        description: "Static pre-rendering and asset optimization ensure pages open instantaneously, reducing bounce rates by up to 60%.",
        badge: "Speed",
        points: ["Zero blocking scripts", "Optimized WebP images", "Global edge caching"],
      },
      {
        title: "Persuasive Visual Flow",
        description: "Strategic placement of trust badges, value propositions, client proof, and clear call-to-actions.",
        badge: "Psychology",
        points: ["Hero value clarity", "Social proof placement", "Clear visual direction"],
      },
      {
        title: "Frictionless Forms",
        description: "Single-step and multi-step intake forms with instant validation and confetti celebration feedback.",
        badge: "Lead Intake",
        points: ["Real-time field validation", "Confetti feedback", "Instant CRM push"],
      },
    ],
    capabilitiesTitle: "Landing Page Deliverables",
    capabilitiesSubtitle: "Conversion Optimization",
    capabilities: [
      {
        title: "Ad Campaign Alignment",
        description: "Ensuring message match between ad copy and landing page headline for higher Quality Scores.",
        badge: "Google Ads",
        points: ["High Quality Score", "Lower CPC", "Direct message match"],
      },
      {
        title: "Conversion Tracking Pixels",
        description: "Complete setup for Google Tag Manager, Meta Pixel, LinkedIn Insight Tag, and GA4 events.",
        badge: "Tracking",
        points: ["GTM container", "Custom event triggers", "Server-side tracking"],
      },
      {
        title: "Mobile-First Conversion Flow",
        description: "Tailored specifically for thumb navigation and tap-to-call / tap-to-WhatsApp triggers.",
        badge: "Mobile",
        points: ["Sticky CTA bar", "One-tap dialing", "Instant WhatsApp chat"],
      },
    ],
    faqs: [
      {
        question: "How fast can Navya build and launch a campaign landing page?",
        answer: "We can deliver and launch a dedicated high-conversion landing page in 3 to 5 business days.",
      },
    ],
    relatedLinks: [
      {
        title: "Website Development",
        description: "Full-scale multi-page website engineering.",
        href: "/services/website-development",
        category: "Services",
      },
      {
        title: "Website Performance",
        description: "Learn about Core Web Vitals optimization.",
        href: "/services/website-performance-optimization",
        category: "Services",
      },
      {
        title: "Get Started",
        description: "Launch your landing page campaign.",
        href: "/get-started",
        category: "Intake",
      },
      {
        title: "Pricing",
        description: "Explore our fixed commercial packages.",
        href: "/pricing",
        category: "Pricing",
      },
    ],
  },

  "/services/ecommerce-website-development": {
    slug: "/services/ecommerce-website-development",
    category: "Services • Commerce",
    title: "Ecommerce Website Development Services | Navya Tech Industry",
    h1: "Ecommerce Website Development Services",
    primaryKeyword: "ecommerce website development services",
    metaDescription: "High-performance ecommerce website development by Navya Tech Industry. Fast catalog browsing, frictionless checkout, and high-converting product pages.",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Ecommerce Website Development" }],
    heroDescription: "Engineering lightning-fast ecommerce digital storefronts that showcase products with elegance and convert shoppers into repeat buyers.",
    heroImageAlt: "Ecommerce Website Development Services",
    heroImageSrc: "/ai3.png",
    heroStats: [
      { label: "Catalog Browsing", value: "Instant" },
      { label: "Checkout Flow", value: "Frictionless" },
      { label: "Payment Gateways", value: "Stripe & Razorpay" },
    ],
    overviewTitle: "Ecommerce Experiences Engineered for High Conversion",
    overviewDescription: "Slow ecommerce stores leak revenue at every click. We build lightning-fast storefronts with instant product filtering, high-resolution visual showcases, mobile-optimized cart drawers, and secure payment integrations.",
    overviewCards: [
      {
        title: "High-Speed Product Catalogs",
        description: "Instantaneous search, category filtering, and product detail viewports that load without page refreshes.",
        badge: "Catalog",
        points: ["Instant client filtering", "Responsive image galleries", "Stock inventory indicators"],
      },
      {
        title: "Frictionless Checkout",
        description: "Streamlined checkout flows with Apple Pay, Google Pay, credit cards, and UPI integration.",
        badge: "Checkout",
        points: ["One-page checkout", "Multiple payment gateways", "Automated email receipts"],
      },
      {
        title: "Mobile Shopping Experience",
        description: "Bottom sheet cart drawers, swipeable image carousels, and sticky 'Buy Now' action bars.",
        badge: "Mobile First",
        points: ["Sticky mobile checkout", "Swipeable galleries", "Touch-friendly inputs"],
      },
    ],
    capabilitiesTitle: "Ecommerce Capabilities",
    capabilitiesSubtitle: "Commerce Architecture",
    capabilities: [
      {
        title: "Secure Payment Integrations",
        description: "Seamless integration with Stripe, Razorpay, PayPal, and local payment processors.",
        badge: "Payments",
        points: ["PCI-DSS compliant", "Multi-currency support", "Fraud detection"],
      },
      {
        title: "Inventory & Order Management",
        description: "Synchronize inventory levels, manage order fulfillment, and send automated tracking numbers.",
        badge: "Operations",
        points: ["Order webhooks", "Inventory tracking", "Automated email dispatch"],
      },
      {
        title: "SEO for Product Pages",
        description: "Rich snippet product schema markup displaying pricing, availability, and star ratings on Google.",
        badge: "Product SEO",
        points: ["Product JSON-LD schema", "Automatic breadcrumbs", "Optimized alt tags"],
      },
    ],
    faqs: [
      {
        question: "Can you build custom product configurators or 3D product visualizers?",
        answer: "Yes! We specialize in custom Three.js/WebGL 3D product viewports where customers can customize colors, materials, and features in real time.",
      },
    ],
    relatedLinks: [
      {
        title: "Ecommerce Industry Solutions",
        description: "Explore our dedicated solutions for online retailers.",
        href: "/industries/ecommerce",
        category: "Industries",
      },
      {
        title: "Ecommerce Pricing",
        description: "View pricing packages for ecommerce platforms.",
        href: "/pricing/ecommerce",
        category: "Pricing",
      },
      {
        title: "Website Development",
        description: "Full-stack web engineering services.",
        href: "/services/website-development",
        category: "Services",
      },
      {
        title: "Get Started",
        description: "Launch your ecommerce storefront.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/services/web-app-development": {
    slug: "/services/web-app-development",
    category: "Services • Applications",
    title: "Web App Development Services | Interactive Platforms by Navya",
    h1: "Web App Development Services",
    primaryKeyword: "web app development services",
    metaDescription: "Custom web application development services by Navya Tech Industry. Modern React/Next.js architectures, real-time data sync, and scalable cloud backends.",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Web App Development" }],
    heroDescription: "Engineering interactive, resilient web applications that streamline complex business processes, automate data pipelines, and delight users.",
    heroImageAlt: "Web App Development Services",
    heroImageSrc: "/ai4.png",
    heroStats: [
      { label: "Architecture", value: "Next.js & React" },
      { label: "Data Pipeline", value: "Real-Time" },
      { label: "Security Model", value: "Role-Based RBAC" },
    ],
    overviewTitle: "Interactive Web Applications Engineered for Complex Workflows",
    overviewDescription: "We engineer full-stack web applications that combine snappy client-side state machines with scalable serverless API architectures. From internal operations tools to customer-facing SaaS platforms, we build applications that scale.",
    overviewCards: [
      {
        title: "Interactive Client State",
        description: "Reactive user interfaces that provide instantaneous visual feedback without unnecessary full page reloads.",
        badge: "Frontend App",
        points: ["Zustand / React Context", "Optimistic UI updates", "Real-time subscriptions"],
      },
      {
        title: "Scalable Cloud Backends",
        description: "Serverless functions, PostgreSQL/Supabase databases, and Redis caching for sub-50ms query responses.",
        badge: "Backend Cloud",
        points: ["Serverless endpoints", "Database indexing", "Redis edge caching"],
      },
      {
        title: "Role-Based Access Control (RBAC)",
        description: "Secure user authentication, permission tiers, and encrypted data storage protecting sensitive company info.",
        badge: "Security",
        points: ["JWT / OAuth 2.0", "Granular permissions", "Encrypted payloads"],
      },
    ],
    capabilitiesTitle: "Web App Development Capabilities",
    capabilitiesSubtitle: "Application Engineering",
    capabilities: [
      {
        title: "Real-Time Dashboards",
        description: "Data visualization panels with live WebSocket updates, interactive charts, and exportable reports.",
        badge: "Dashboards",
        points: ["Chart.js / Recharts", "Live telemetry", "Data export"],
      },
      {
        title: "Workflow Automation Engines",
        description: "Automate manual tasks with background jobs, scheduled cron tasks, and webhook triggers.",
        badge: "Automation",
        points: ["Background task queue", "Scheduled cron triggers", "Third-party syncing"],
      },
      {
        title: "Progressive Web App (PWA)",
        description: "Installable web applications with offline capabilities, home screen icons, and push notifications.",
        badge: "PWA",
        points: ["Service worker caching", "Web app manifest", "Offline fallback"],
      },
    ],
    faqs: [
      {
        question: "Can Navya build an MVP for our startup web application?",
        answer: "Yes. We specialize in building production-ready MVPs with rapid 2 to 4 week turnarounds so you can validate with real users quickly.",
      },
    ],
    relatedLinks: [
      {
        title: "SaaS Industry Solutions",
        description: "Explore our dedicated solutions for SaaS companies.",
        href: "/industries/saas",
        category: "Industries",
      },
      {
        title: "Custom Web Development",
        description: "Explore custom web engineering services.",
        href: "/services/custom-web-development",
        category: "Services",
      },
      {
        title: "Pricing Matrix",
        description: "View our package options.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Submit your web app specifications.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/services/website-redesign": {
    slug: "/services/website-redesign",
    category: "Services • Modernization",
    title: "Website Redesign Services | Modernize Your Digital Presence by Navya",
    h1: "Website Redesign Services",
    primaryKeyword: "website redesign services",
    metaDescription: "Transform outdated, slow websites into high-converting, modern digital experiences. Seamless content migration and zero ranking loss with Navya Tech Industry.",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Website Redesign" }],
    heroDescription: "Modernize your digital presence. We transform legacy, bloated websites into sleek, lightning-fast Next.js platforms while protecting existing Google rankings.",
    heroImageAlt: "Website Redesign Services",
    heroImageSrc: "/ai5.png",
    heroStats: [
      { label: "SEO Migration", value: "301 Safe" },
      { label: "Speed Improvement", value: "Up to 4x" },
      { label: "Conversion Lift", value: "Immediate" },
    ],
    overviewTitle: "From Outdated Web Property to Market-Leading Digital Asset",
    overviewDescription: "An outdated website damages credibility, frustrates mobile visitors, and suppresses conversion rates. We redesign your website with modern claymorphic visual polish, sub-second load speeds, and strict 301 redirect mapping to preserve SEO equity.",
    overviewCards: [
      {
        title: "Complete Visual Evolution",
        description: "Replace tired template layouts with modern dark aesthetics, tactile depth, refined typography, and engaging micro-motion.",
        badge: "Visual Upgrade",
        points: ["Modern claymorphic UI", "Contemporary typography", "Elevated brand prestige"],
      },
      {
        title: "SEO Protection & 301 Mapping",
        description: "Carefully auditing existing URLs, meta tags, and backlinks so your organic search traffic continues climbing uninterrupted.",
        badge: "SEO Protection",
        points: ["1-to-1 URL redirect map", "Metadata preservation", "Zero broken links"],
      },
      {
        title: "Speed & Core Web Vitals Rebirth",
        description: "Moving from slow, bloated CMS plugins to streamlined Next.js code for dramatic score improvements.",
        badge: "Speed Rebirth",
        points: ["Lighthouse score 95+", "Sub-second LCP", "Zero render blocking"],
      },
    ],
    capabilitiesTitle: "Redesign Deliverables",
    capabilitiesSubtitle: "Migration Standards",
    capabilities: [
      {
        title: "Content Extraction & Refinement",
        description: "Migrating and sharpening existing copy, updating outdated imagery, and structuring clear messaging.",
        badge: "Content",
        points: ["Copy refinement", "Image optimization", "Structured hierarchy"],
      },
      {
        title: "Mobile UX Overhaul",
        description: "Re-engineering mobile navigation, button tap targets, and touch interactions for mobile shoppers.",
        badge: "Mobile Overhaul",
        points: ["Touch navigation", "Fast mobile drawer", "Zero horizontal scroll"],
      },
      {
        title: "Zero-Downtime Cutover",
        description: "Staged DNS switch and deployment ensuring your existing visitors and customers experience zero disruption.",
        badge: "Cutover",
        points: ["Staged testing environment", "Instant DNS cutover", "Continuous monitoring"],
      },
    ],
    faqs: [
      {
        question: "Will redesigning my website cause a drop in Google rankings?",
        answer: "No. Because we implement rigorous 301 redirect mapping, retain historical URLs where beneficial, and improve Core Web Vitals, organic rankings typically increase.",
      },
    ],
    relatedLinks: [
      {
        title: "Website Performance Optimization",
        description: "Learn how we optimize speed and Core Web Vitals.",
        href: "/services/website-performance-optimization",
        category: "Services",
      },
      {
        title: "Website Design",
        description: "Explore our UI/UX design capabilities.",
        href: "/services/website-design",
        category: "Services",
      },
      {
        title: "Build Website",
        description: "Explore our turnkey website build framework.",
        href: "/build-website",
        category: "Commercial",
      },
      {
        title: "Get Started",
        description: "Request a website redesign audit.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/services/website-maintenance": {
    slug: "/services/website-maintenance",
    category: "Services • Operations",
    title: "Website Maintenance Services | Ongoing Support & SLA by Navya",
    h1: "Website Maintenance Services",
    primaryKeyword: "website maintenance services",
    metaDescription: "Reliable website maintenance and ongoing support services by Navya Tech Industry. Security updates, content updates, uptime monitoring, and $50/request packages.",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Website Maintenance" }],
    heroDescription: "Keep your digital presence secure, fast, and constantly updated. Dedicated maintenance, rapid turnaround updates, and 24/7 uptime monitoring.",
    heroImageAlt: "Website Maintenance Services",
    heroImageSrc: "/ai1.png",
    heroStats: [
      { label: "Uptime SLA", value: "99.99%" },
      { label: "Ticket Turnaround", value: "< 24 Hours" },
      { label: "Pay Per Request", value: "$50 / ₹3,900" },
    ],
    overviewTitle: "Proactive Website Maintenance & Technical Peace of Mind",
    overviewDescription: "Your website is an active commercial asset that requires regular dependency maintenance, security patching, telemetry monitoring, and rapid copy/service updates. Navya provides responsive ongoing support so your team can focus on growth.",
    overviewCards: [
      {
        title: "Security Patching & Audits",
        description: "Routine dependency updates, SSL certificate renewal validation, and automated vulnerability vulnerability scans.",
        badge: "Security",
        points: ["Automated npm audit checks", "SSL / DNS renewal tracking", "Zero-day vulnerability fixes"],
      },
      {
        title: "Rapid Content & Feature Updates",
        description: "Need a new service page, team member profile, or pricing update? Submit a ticket for rapid 24-hour turnaround.",
        badge: "Rapid Updates",
        points: ["Under 24-hour turnaround", "Direct engineer handling", "Staging preview review"],
      },
      {
        title: "Continuous Uptime & Telemetry",
        description: "Real-time monitoring that alerts our engineering team immediately if a third-party API or server encounters issues.",
        badge: "Telemetry",
        points: ["24/7 endpoint ping", "Error tracking", "Performance baseline monitoring"],
      },
    ],
    capabilitiesTitle: "Maintenance Package Inclusions",
    capabilitiesSubtitle: "Support Coverage",
    capabilities: [
      {
        title: "On-Demand Change Requests",
        description: "Flexible pay-per-request maintenance at $50 / request with zero forced monthly contracts.",
        badge: "$50 / Req",
        points: ["No minimum retainers", "Transparent pricing", "Immediate priority"],
      },
      {
        title: "Core Web Vitals Health Checks",
        description: "Periodic audits ensuring page load speeds and search engine rankings remain at peak performance.",
        badge: "Performance",
        points: ["Monthly CWV reports", "Image optimization passes", "Cache verification"],
      },
      {
        title: "Database & Asset Backups",
        description: "Automated daily and weekly code/database snapshots ensuring instant disaster recovery.",
        badge: "Backups",
        points: ["Automated snapshots", "Version control history", "Instant rollback"],
      },
    ],
    faqs: [
      {
        question: "Are we required to sign a monthly contract for maintenance?",
        answer: "No. We offer flexible on-demand maintenance at $50 / ₹3,900 per request, as well as dedicated monthly retainers for businesses with high update frequency.",
      },
    ],
    relatedLinks: [
      {
        title: "Performance Optimization",
        description: "Explore Core Web Vitals optimization.",
        href: "/services/website-performance-optimization",
        category: "Services",
      },
      {
        title: "Website Development",
        description: "Explore our web development services.",
        href: "/services/website-development",
        category: "Services",
      },
      {
        title: "Pricing Packages",
        description: "View transparent maintenance and web packages.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Contact Support",
        description: "Submit a maintenance request.",
        href: "/contact",
        category: "Contact",
      },
    ],
  },

  "/services/website-performance-optimization": {
    slug: "/services/website-performance-optimization",
    category: "Services • Performance",
    title: "Website Performance Optimization Services | Core Web Vitals by Navya",
    h1: "Website Performance Optimization Services",
    primaryKeyword: "website performance optimization services",
    metaDescription: "Speed up your website and dominate Google rankings. Expert Core Web Vitals optimization, asset compression, JavaScript splitting, and sub-second loading by Navya.",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "Performance Optimization" }],
    heroDescription: "Eliminate page lag and boost search rankings. We optimize Core Web Vitals, asset pipelines, and JavaScript execution to deliver blazing sub-second load times.",
    heroImageAlt: "Website Performance Optimization Services",
    heroImageSrc: "/ai2.png",
    heroStats: [
      { label: "Lighthouse Target", value: "95-100" },
      { label: "Largest Contentful Paint", value: "< 1.2s" },
      { label: "Cumulative Layout Shift", value: "0.00" },
    ],
    overviewTitle: "Engineering Sub-Second Speed for Maximum Conversion",
    overviewDescription: "Every 100ms delay in page load time reduces visitor conversion rates by up to 7%. We systematically eliminate render-blocking CSS, compress media assets, optimize JavaScript execution trees, and leverage edge CDN caching to deliver unbeatable speed.",
    overviewCards: [
      {
        title: "Largest Contentful Paint (LCP)",
        description: "Optimizing critical hero images, font loading, and server response times to display main content in under 1.2 seconds.",
        badge: "LCP",
        points: ["Fetch priority hints", "Modern WebP/AVIF formats", "Zero render-blocking assets"],
      },
      {
        title: "Interaction to Next Paint (INP)",
        description: "Minimizing main-thread JavaScript execution so every click, tap, and scroll responds instantaneously.",
        badge: "INP",
        points: ["Code splitting", "Debounced event handlers", "Off-thread Web Workers"],
      },
      {
        title: "Cumulative Layout Shift (CLS)",
        description: "Locking element dimensions and utilizing CSS aspect-ratio properties to eliminate annoying content jumping.",
        badge: "CLS",
        points: ["Explicit width/height attributes", "Font display swap", "Reserved layout space"],
      },
    ],
    capabilitiesTitle: "Optimization Disciplines",
    capabilitiesSubtitle: "Deep Technical Tuning",
    capabilities: [
      {
        title: "Asset & Image Pipeline",
        description: "Automated generation of next-gen WebP/AVIF images with responsive srcset attributes.",
        badge: "Image Engine",
        points: ["Lossless compression", "Responsive srcset", "Native lazy loading"],
      },
      {
        title: "JavaScript Bundle Diet",
        description: "Tree-shaking unused libraries, eliminating dead code, and dynamically importing heavy components.",
        badge: "Bundle Diet",
        points: ["Dynamic dynamic imports", "Tree-shaking audits", "Minimal third-party scripts"],
      },
      {
        title: "Edge CDN Caching Strategy",
        description: "Configuring cache-control headers, stale-while-revalidate policies, and edge-side rendering.",
        badge: "Edge Cache",
        points: ["Global edge caching", "Brotli compression", "Instant cache invalidation"],
      },
    ],
    faqs: [
      {
        question: "Can you optimize performance on an existing website built by another agency?",
        answer: "Yes. We perform a complete performance audit and apply targeted optimizations to your existing codebase or provide a streamlined Next.js migration.",
      },
    ],
    relatedLinks: [
      {
        title: "Website SEO Services",
        description: "Explore technical SEO and organic search visibility.",
        href: "/services/seo",
        category: "Services",
      },
      {
        title: "Website Development",
        description: "Full-stack web engineering services.",
        href: "/services/website-development",
        category: "Services",
      },
      {
        title: "Pricing",
        description: "View our package options.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Request a performance audit.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },

  "/services/seo": {
    slug: "/services/seo",
    category: "Services • Growth",
    title: "SEO Services | Technical SEO & Search Architecture by Navya",
    h1: "Technical SEO Services",
    primaryKeyword: "seo services",
    metaDescription: "Technical SEO services by Navya Tech Industry. Built-in structured data, crawl-optimized architecture, schema markup, and guaranteed search engine indexation.",
    breadcrumbs: [{ label: "Services", href: "/services" }, { label: "SEO Services" }],
    heroDescription: "Engineering search-engine-native architectures that earn top Google rankings through clean semantics, structured JSON-LD schema, and lightning-fast indexation.",
    heroImageAlt: "Technical SEO Services",
    heroImageSrc: "/ai3.png",
    heroStats: [
      { label: "Schema Markup", value: "JSON-LD" },
      { label: "Crawl Indexation", value: "100% Valid" },
      { label: "Canonical Structure", value: "Enforced" },
    ],
    overviewTitle: "Search Engine Optimization Built into the Codebase",
    overviewDescription: "We do not rely on superficial SEO plugins or spammy tactics. We engineer your website with semantic HTML5 hierarchy, comprehensive JSON-LD schema (Organization, Service, FAQ, Breadcrumbs), clean canonical hierarchy, and dynamic meta management.",
    overviewCards: [
      {
        title: "Structured JSON-LD Schema",
        description: "Embedding rich structured data that enables rich search results, FAQ carousels, and enhanced brand knowledge panels on Google.",
        badge: "Rich Snippets",
        points: ["Organization schema", "Service and Offer schemas", "FAQ and Breadcrumb markup"],
      },
      {
        title: "Crawl Optimization & Sitemaps",
        description: "Automated XML sitemaps, properly configured robots.txt directives, and clean URL routing for effortless search crawler indexing.",
        badge: "Crawling",
        points: ["Dynamic XML sitemaps", "Robots.txt configuration", "Zero orphan pages"],
      },
      {
        title: "Content & Keyword Architecture",
        description: "Structuring H1/H2 heading hierarchy, optimized title tags, and natural keyword density without repetitive stuffing.",
        badge: "On-Page SEO",
        points: ["Single authoritative H1", "Descriptive alt text", "Unique meta descriptions"],
      },
    ],
    capabilitiesTitle: "Technical SEO Inclusions",
    capabilitiesSubtitle: "Search Foundations",
    capabilities: [
      {
        title: "Automated OpenGraph Social Tags",
        description: "Dynamic preview cards when your links are shared on LinkedIn, X/Twitter, WhatsApp, and Slack.",
        badge: "Social Graph",
        points: ["Dynamic OG titles", "High-res share cards", "Twitter card tags"],
      },
      {
        title: "Internal Linking Architecture",
        description: "Strategically linking related service, industry, and commercial pages to maximize authority flow.",
        badge: "PageRank Flow",
        points: ["Descriptive anchor text", "Zero dead links", "Contextual recommendations"],
      },
      {
        title: "Google Search Console Ready",
        description: "Full verification setup, sitemap submission, and indexing monitoring to ensure immediate Google visibility.",
        badge: "Search Console",
        points: ["Sitemap submission", "Indexation audit", "Mobile usability verification"],
      },
    ],
    faqs: [
      {
        question: "Do you make unrealistic ranking guarantees?",
        answer: "No. We do not make false promises of '#1 overnight rankings.' Instead, we build flawless technical foundations and authoritative content structures that Google consistently rewards.",
      },
    ],
    relatedLinks: [
      {
        title: "Website Performance",
        description: "Core Web Vitals and speed optimization.",
        href: "/services/website-performance-optimization",
        category: "Services",
      },
      {
        title: "Website Development",
        description: "Explore our web development services.",
        href: "/services/website-development",
        category: "Services",
      },
      {
        title: "Pricing Matrix",
        description: "View our package options.",
        href: "/pricing",
        category: "Pricing",
      },
      {
        title: "Get Started",
        description: "Audit your website SEO.",
        href: "/get-started",
        category: "Intake",
      },
    ],
  },
};
