import { BlogCategoryHub } from "./types";

export const blogCategories: Record<string, BlogCategoryHub> = {
  "/blog/website-development": {
    slug: "/blog/website-development",
    title: "Website Development Articles & Engineering Insights | Navya Blog",
    h1: "Website Development Insights",
    metaDescription: "In-depth articles on modern website development, Next.js architecture, build costs, project timelines, custom code vs builders, and engineering best practices.",
    categoryLabel: "WEBSITE DEVELOPMENT",
    heroDescription: "Explore practical guides, architectural breakdowns, cost calculators, and development methodologies for engineering high-performance modern web platforms.",
    featuredArticleSlug: "/blog/how-to-build-a-business-website",
    articleSlugs: [
      "/blog/how-to-build-a-business-website",
      "/blog/how-much-does-it-cost-to-build-a-website",
      "/blog/how-long-does-it-take-to-build-a-website",
      "/blog/how-to-create-a-professional-website",
      "/blog/custom-website-vs-website-builder",
      "/blog/what-does-a-business-website-need",
      "/blog/website-development-cost",
      "/blog/website-building-process",
    ],
    relatedServiceHref: "/services/website-development",
    relatedServiceTitle: "Website Development Services",
    heroImageAlt: "Website Development Insights",
  },

  "/blog/website-design": {
    slug: "/blog/website-design",
    title: "Website Design & UI/UX Insights | Navya Blog",
    h1: "Website Design & UI/UX",
    metaDescription: "Explore UI/UX design principles, claymorphic aesthetics, typography hierarchy, responsive spatial tokens, and high-converting interface design.",
    categoryLabel: "WEBSITE DESIGN",
    heroDescription: "Master the art and science of human-centered web design, tactile claymorphic aesthetics, fluid responsive layouts, and conversion-focused user interfaces.",
    featuredArticleSlug: "/blog/how-to-create-a-professional-website",
    articleSlugs: [
      "/blog/how-to-create-a-professional-website",
      "/blog/what-makes-a-good-business-website",
      "/blog/benefits-of-3d-web-design",
      "/blog/custom-website-vs-website-builder",
    ],
    relatedServiceHref: "/services/website-design",
    relatedServiceTitle: "Website Design Services",
    heroImageAlt: "Website Design & UI/UX",
  },

  "/blog/3d-websites": {
    slug: "/blog/3d-websites",
    title: "3D Websites & WebGL Engineering Articles | Navya Blog",
    h1: "3D Websites & WebGL Engineering",
    metaDescription: "Articles on interactive 3D web design, WebGL graphics pipelines, Three.js shaders, 60fps performance tuning, and business ROI of 3D spatial experiences.",
    categoryLabel: "3D WEBSITES",
    heroDescription: "Dive deep into hardware-accelerated 3D graphics, WebGL rendering pipelines, GLSL shaders, and the commercial impact of interactive spatial web design.",
    featuredArticleSlug: "/blog/what-is-a-3d-website",
    articleSlugs: [
      "/blog/what-is-a-3d-website",
      "/blog/how-3d-websites-work",
      "/blog/3d-website-vs-traditional-website",
      "/blog/3d-website-development",
      "/blog/benefits-of-3d-web-design",
      "/blog/is-a-3d-website-good-for-business",
      "/blog/webgl-website-development",
    ],
    relatedServiceHref: "/services/3d-website-development",
    relatedServiceTitle: "3D Website Development",
    heroImageAlt: "3D Websites & WebGL Engineering",
  },

  "/blog/business-websites": {
    slug: "/blog/business-websites",
    title: "Business Website Strategy & Conversion | Navya Blog",
    h1: "Business Website Strategy",
    metaDescription: "Actionable articles for founders and business leaders: website ROI, avoiding common web mistakes, customer journeys, agency evaluation, and digital asset ownership.",
    categoryLabel: "BUSINESS WEBSITES",
    heroDescription: "Strategic insights for founders, executives, and marketing leaders on building high-trust corporate platforms that generate qualified revenue 24/7.",
    featuredArticleSlug: "/blog/why-businesses-need-a-website",
    articleSlugs: [
      "/blog/why-businesses-need-a-website",
      "/blog/what-makes-a-good-business-website",
      "/blog/business-website-mistakes",
      "/blog/website-vs-social-media",
      "/blog/how-to-choose-a-website-development-company",
      "/blog/how-to-build-a-business-website",
      "/blog/what-does-a-business-website-need",
    ],
    relatedServiceHref: "/services/business-website-development",
    relatedServiceTitle: "Business Website Development",
    heroImageAlt: "Business Website Strategy",
  },

  "/blog/seo": {
    slug: "/blog/seo",
    title: "Technical SEO & Search Optimization Articles | Navya Blog",
    h1: "Technical SEO & Search Optimization",
    metaDescription: "Master technical SEO, Google Search Console indexing, JSON-LD structured schemas, Core Web Vitals optimization, and actionable search ranking checklists.",
    categoryLabel: "TECHNICAL SEO",
    heroDescription: "Authoritative guides on technical SEO architecture, structured JSON-LD schemas, Core Web Vitals performance tuning, and dominating Google search rankings.",
    featuredArticleSlug: "/blog/technical-seo-for-websites",
    articleSlugs: [
      "/blog/website-seo-basics",
      "/blog/technical-seo-for-websites",
      "/blog/core-web-vitals",
      "/blog/how-to-get-a-website-on-google",
      "/blog/website-seo-checklist",
    ],
    relatedServiceHref: "/services/seo",
    relatedServiceTitle: "Technical SEO Services",
    heroImageAlt: "Technical SEO & Search Optimization",
  },

  "/blog/web-development": {
    slug: "/blog/web-development",
    title: "Modern Web Development Technologies & Standards | Navya Blog",
    h1: "Modern Web Development",
    metaDescription: "Articles on full-stack web engineering, React 19, Next.js 15, TypeScript architectures, serverless edge runtimes, and progressive web applications.",
    categoryLabel: "WEB DEVELOPMENT",
    heroDescription: "Explore advanced web engineering patterns, modern framework architectures, TypeScript paradigms, and edge-native full-stack development practices.",
    featuredArticleSlug: "/blog/custom-website-vs-website-builder",
    articleSlugs: [
      "/blog/custom-website-vs-website-builder",
      "/blog/website-building-process",
      "/blog/how-long-does-it-take-to-build-a-website",
      "/blog/3d-website-development",
      "/blog/webgl-website-development",
    ],
    relatedServiceHref: "/services/web-app-development",
    relatedServiceTitle: "Web App Development",
    heroImageAlt: "Modern Web Development",
  },
};
